"use client";
import Link from "next/link";
import { useState } from "react";
import { playPianoRate } from "@/lib/piano-sampler";

type Note="Dó"|"Ré"|"Mi"|"Fá"|"Sol"|"Lá"|"Si";
const rate:Record<Note,number>={"Dó":1,"Ré":Math.pow(2,2/12),"Mi":Math.pow(2,4/12),"Fá":Math.pow(2,5/12),"Sol":Math.pow(2,7/12),"Lá":Math.pow(2,9/12),"Si":Math.pow(2,11/12)};
function play(n:Note,short=false){void playPianoRate(rate[n]); void short}\nconst css=`.shell{max-width:760px;margin:32px auto;padding:28px;background:#fff;border:1px solid #e4eaf1;border-radius:28px;box-shadow:0 16px 44px #2a456515}.center{text-align:center}.big{font-size:72px}small{font-size:11px;text-transform:uppercase;letter-spacing:.08em;font-weight:900;color:#6c75cd}h1{font-size:clamp(29px,5vw,44px);margin:6px 0 10px}p{color:#68768b;line-height:1.6}.duo{display:block;width:min(360px,100%);min-height:52px;margin:24px auto 14px;border:0;border-radius:16px;background:#58cc02;color:#fff;font-weight:950;box-shadow:0 5px 0 #46a302}.back{font-weight:900;color:#5b7193;text-decoration:none}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:22px}.grid button{min-height:90px;border:2px solid #e0e6ed;border-radius:20px;background:#fff;font-weight:950;color:#40516a}.msg{margin-top:18px;padding:15px;border-radius:16px;background:#fff3e1;color:#765b29;font-weight:900}.msg.ok{background:#efffe9;color:#3a7341}@media(max-width:620px){.shell{margin:15px 12px;padding:20px}.grid{grid-template-columns:1fr}}`;
function Intro({emoji,title,story,onStart}:{emoji:string;title:string;story:string;onStart:()=>void}){return <section className="shell center"><div className="big">{emoji}</div><small>Historinha</small><h1>{title}</h1><p>{story}</p><button className="duo" onClick={onStart}>COMEÇAR</button><style jsx>{css}</style></section>}
function Done({text,onRestart}:{text:string;onRestart:()=>void}){return <section className="shell center"><div className="big">🌟</div><h1>{text}</h1><button className="duo" onClick={onRestart}>JOGAR DE NOVO</button><Link className="back" href="/jogos">Outro jogo</Link><style jsx>{css}</style></section>}

export function ColorPathGame({story}:{story:string}){const rounds:Note[][]=[["Dó","Ré"],["Mi","Sol"],["Dó","Mi","Ré"],["Sol","Ré","Mi","Dó"]];const [s,setS]=useState(false),[r,setR]=useState(0),[p,setP]=useState(0),[m,setM]=useState<string|null>(null);const q=rounds[r];if(!s)return <Intro emoji="🌈" title="Caminho das Cores" story={story} onStart={()=>setS(true)}/>;if(!q)return <Done text="Caminho completo!" onRestart={()=>{setR(0);setP(0)}}/>;const opts:Note[]=["Dó","Ré","Mi","Sol"];function hit(n:Note){play(n);if(n!==q[p]){setP(0);setM("Quase. Volte ao início.");return}if(p+1===q.length){setM("✓ Caminho completo!");setTimeout(()=>{setR(v=>v+1);setP(0);setM(null)},500)}else{setP(v=>v+1);setM(null)}}return <section className="shell center"><small>Trilha {r+1} de {rounds.length}</small><h1>{q.map((n,i)=><span key={i} style={{opacity:i===p?1:.35,margin:6}}>{n}</span>)}</h1><div className="grid">{opts.map(n=><button key={n} onClick={()=>hit(n)}>{n}</button>)}</div>{m&&<div className={`msg ${m.startsWith("✓")?"ok":""}`}>{m}</div>}<style jsx>{css}</style></section>}

export function TrainRhythmGame({story}:{story:string}){const rounds=["DEVAGAR","RÁPIDO","PARE","CONTINUE","RÁPIDO","PARE"];const [s,setS]=useState(false),[r,setR]=useState(0),[m,setM]=useState<string|null>(null);const q=rounds[r];if(!s)return <Intro emoji="🚂" title="Trem do Ritmo" story={story} onStart={()=>setS(true)}/>;if(!q)return <Done text="O trem chegou!" onRestart={()=>setR(0)}/>;const o=["🐢 DEVAGAR","🐇 RÁPIDO","🛑 PARE","🟢 CONTINUE"];function hit(v:string){if(!v.includes(q)){setM("Quase. Veja o sinal outra vez.");return}setM("✓ Muito bem!");setTimeout(()=>{setR(x=>x+1);setM(null)},450)}return <section className="shell center"><small>Estação {r+1} de {rounds.length}</small><div className="big">🚂</div><h1>{q}</h1><div className="grid">{o.map(v=><button key={v} onClick={()=>hit(v)}>{v}</button>)}</div>{m&&<div className={`msg ${m.startsWith("✓")?"ok":""}`}>{m}</div>}<style jsx>{css}</style></section>}

export function LambAdventureGame({story}:{story:string}){const rounds:Note[][]=[["Mi","Ré"],["Dó","Ré","Mi"],["Mi","Mi","Mi"],["Ré","Ré","Mi","Sol"]];const [s,setS]=useState(false),[r,setR]=useState(0),[p,setP]=useState(0),[m,setM]=useState<string|null>(null);const q=rounds[r];if(!s)return <Intro emoji="🐑👧" title="Ajude o Cordeirinho" story={story} onStart={()=>setS(true)}/>;if(!q)return <Done text="Nino encontrou Maria!" onRestart={()=>{setR(0);setP(0)}}/>;function hit(n:Note){play(n);if(n!==q[p]){setP(0);setM("Quase. Nino espera outra tentativa.");return}if(p+1===q.length){setM("✓ Nino avançou!");setTimeout(()=>{setR(x=>x+1);setP(0);setM(null)},500)}else{setP(x=>x+1);setM(null)}}return <section className="shell center"><small>Parte {r+1} de {rounds.length}</small><h1>🐑 {"·".repeat(r+1)} 👧</h1><p>{q.map((n,i)=><b key={i} style={{opacity:i===p?1:.3,margin:5}}>{n}</b>)}</p><div className="grid">{(["Dó","Ré","Mi","Sol"] as Note[]).map(n=><button key={n} onClick={()=>hit(n)}>{n}</button>)}</div>{m&&<div className={`msg ${m.startsWith("✓")?"ok":""}`}>{m}</div>}<style jsx>{css}</style></section>}

export function StaffToKeyGame({story}:{story:string}){const rounds:Note[]=["Mi","Sol","Fá","Ré","Dó","Lá"];const [s,setS]=useState(false),[r,setR]=useState(0),[m,setM]=useState<string|null>(null);const q=rounds[r];if(!s)return <Intro emoji="🎼🎹" title="Pauta → Tecla" story={story} onStart={()=>setS(true)}/>;if(!q)return <Done text="Notas encontradas!" onRestart={()=>setR(0)}/>;function hit(n:Note){play(n);if(n!==q){setM("Quase. Olhe a nota outra vez.");return}setM("✓ Muito bem!");setTimeout(()=>{setR(x=>x+1);setM(null)},450)}return <section className="shell center"><small>Nota {r+1} de {rounds.length}</small><h1>𝄞　{q}</h1><p>Encontre a tecla correspondente.</p><div className="grid">{(["Dó","Ré","Mi","Fá","Sol","Lá"] as Note[]).map(n=><button key={n} onClick={()=>hit(n)}>{n}</button>)}</div>{m&&<div className={`msg ${m.startsWith("✓")?"ok":""}`}>{m}</div>}<style jsx>{css}</style></section>}

export function BuildMeasureGame({story}:{story:string}){const figs=[{s:"𝅘𝅥",b:1},{s:"𝅗𝅥",b:2},{s:"𝅝",b:4}];const [s,setS]=useState(false),[r,setR]=useState(0),[total,setTotal]=useState(0),[m,setM]=useState<string|null>(null);if(!s)return <Intro emoji="⏱️🎵" title="Construa o Compasso" story={story} onStart={()=>setS(true)}/>;if(r>=3)return <Done text="Compassos completos!" onRestart={()=>{setR(0);setTotal(0)}}/>;function add(b:number){if(total+b>4){setM("Passou de 4. Tente outra figura.");return}const n=total+b;setTotal(n);setM(n===4?"✓ Compasso completo!":null)}return <section className="shell center"><small>Desafio {r+1} de 3</small><h1>4/4 · {total}/4</h1><div className="grid">{figs.map(f=><button key={f.s} onClick={()=>add(f.b)}><span style={{fontSize:44}}>{f.s}</span><br/>{f.b} {f.b===1?"tempo":"tempos"}</button>)}</div>{total===4&&<button className="duo" onClick={()=>{setR(x=>x+1);setTotal(0);setM(null)}}>CONTINUAR</button>}{m&&<div className={`msg ${m.startsWith("✓")?"ok":""}`}>{m}</div>}<style jsx>{css}</style></section>}

export function FingerMasterGame({story}:{story:string}){const ms=["Direita · 1","Esquerda · 5","Direita · 3","Esquerda · 2","Direita · 4","Esquerda · 1"];const [s,setS]=useState(false),[r,setR]=useState(0),[m,setM]=useState<string|null>(null);const q=ms[r];if(!s)return <Intro emoji="🖐️" title="Mestre dos Dedos" story={story} onStart={()=>setS(true)}/>;if(!q)return <Done text="Missão concluída!" onRestart={()=>setR(0)}/>;function hit(v:string){if(v!==q){setM("Quase. Veja a mão e o dedo.");return}setM("✓ Muito bem!");setTimeout(()=>{setR(x=>x+1);setM(null)},450)}const opts=["Direita · 1","Direita · 3","Direita · 4","Esquerda · 1","Esquerda · 2","Esquerda · 5"];return <section className="shell center"><small>Missão {r+1} de {ms.length}</small><h1>{q}</h1><div className="grid">{opts.map(v=><button key={v} onClick={()=>hit(v)}>{v.startsWith("Direita")?"✋":"🤚"} {v}</button>)}</div>{m&&<div className={`msg ${m.startsWith("✓")?"ok":""}`}>{m}</div>}<style jsx>{css}</style></section>}

export function ArticulationGame({story}:{story:string}){type A="legato"|"staccato";const rounds:A[]=["legato","staccato","staccato","legato","staccato","legato"];const [s,setS]=useState(false),[r,setR]=useState(0),[heard,setHeard]=useState(false),[m,setM]=useState<string|null>(null);const q=rounds[r];if(!s)return <Intro emoji="〰️ • • •" title="Legato ou Staccato?" story={story} onStart={()=>setS(true)}/>;if(!q)return <Done text="Muito bem!" onRestart={()=>setR(0)}/>;async function hear(){setHeard(true);for(const n of ["Dó","Mi","Sol"] as Note[]){play(n,q==="staccato");await new Promise(x=>setTimeout(x,q==="staccato"?260:390))}}function hit(v:A){if(v!==q){setM("Quase. Ouça outra vez.");return}setM("✓ Muito bem!");setTimeout(()=>{setR(x=>x+1);setHeard(false);setM(null)},450)}return <section className="shell center"><small>Rodada {r+1} de {rounds.length}</small><h1>Desliza ou salta?</h1><button className="duo" onClick={()=>void hear()}>🔊 OUVIR</button><div className="grid"><button disabled={!heard} onClick={()=>hit("legato")}>〰️ LEGATO</button><button disabled={!heard} onClick={()=>hit("staccato")}>• • • STACCATO</button></div>{m&&<div className={`msg ${m.startsWith("✓")?"ok":""}`}>{m}</div>}<style jsx>{css}</style></section>}

export function CompleteMelodyGame({story}:{story:string}){const qs=[{p:["Dó","Ré","Mi"] as Note[],a:"Fá" as Note,o:["Dó","Fá"] as Note[]},{p:["Sol","Mi","Ré"] as Note[],a:"Dó" as Note,o:["Dó","Lá"] as Note[]},{p:["Dó","Mi","Sol"] as Note[],a:"Dó" as Note,o:["Dó","Ré"] as Note[]}];const [s,setS]=useState(false),[r,setR]=useState(0),[heard,setHeard]=useState(false),[m,setM]=useState<string|null>(null);const q=qs[r];if(!s)return <Intro emoji="🧩🎵" title="Complete a Melodia" story={story} onStart={()=>setS(true)}/>;if(!q)return <Done text="Melodias completas!" onRestart={()=>setR(0)}/>;async function hear(){setHeard(true);for(const n of q.p){play(n);await new Promise(x=>setTimeout(x,420))}}function hit(n:Note){play(n);if(n!==q.a){setM("Quase. Há um final que fecha melhor.");return}setM("✓ A melodia encontrou o final!");setTimeout(()=>{setR(x=>x+1);setHeard(false);setM(null)},500)}return <section className="shell center"><small>Melodia {r+1} de {qs.length}</small><h1>{q.p.join(" · ")} · ?</h1><button className="duo" onClick={()=>void hear()}>🔊 OUVIR</button><div className="grid">{q.o.map(n=><button key={n} disabled={!heard} onClick={()=>hit(n)}>{n}</button>)}</div>{m&&<div className={`msg ${m.startsWith("✓")?"ok":""}`}>{m}</div>}<style jsx>{css}</style></section>}
