"use client";
import { useMemo, useRef, useState } from "react";
import { lessonTemplates, type AgeBand, type BlockKind } from "@/lib/suzuki-lessons";
import styles from "./library-panel.module.css";

const kinds: {id:"all"|BlockKind;label:string}[]=[{id:"all",label:"Tudo"},{id:"movement",label:"Corpo"},{id:"ear",label:"Ouvido"},{id:"piano",label:"Piano"},{id:"repertoire",label:"Repertório"},{id:"closing",label:"Fecho"}];

export function LibraryPanel(){
 const [age,setAge]=useState<"all"|AgeBand>("all"),[kind,setKind]=useState<"all"|BlockKind>("all"),[query,setQuery]=useState("");
 const inputRef=useRef<HTMLInputElement|null>(null);
 const blocks=useMemo(()=>lessonTemplates.flatMap((lesson)=>lesson.blocks.map((block)=>({lesson,block}))).filter(({lesson,block})=>(age==="all"||lesson.ageBand===age)&&(kind==="all"||block.kind===kind)&&`${lesson.title} ${lesson.repertoire} ${block.title} ${block.objective}`.toLowerCase().includes(query.toLowerCase())),[age,kind,query]);
 function clear(){setQuery("");requestAnimationFrame(()=>inputRef.current?.focus())}
 return <div className={styles.page}><header><span>BIBLIOTECA</span><h1>Blocos para ensinar. Não um arcade separado da aula.</h1><p>Procure um bloco, veja o objetivo e use-o para substituir uma parte da sessão em segundos.</p></header><div className={styles.filters}><div className={styles.searchWrap}><input ref={inputRef} aria-label="Procurar bloco" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Procurar por objetivo, música ou atividade…"/>{query&&<button type="button" onClick={clear} aria-label="Limpar pesquisa">×</button>}</div><select aria-label="Filtrar por idade" value={age} onChange={(event)=>setAge(event.target.value as "all"|AgeBand)}><option value="all">Todas as idades</option><option value="2-3">2–3</option><option value="4-5">4–5</option><option value="6-8">6–8</option></select></div><div className={styles.kinds}>{kinds.map((item)=><button key={item.id} data-active={kind===item.id} onClick={()=>setKind(item.id)}>{item.label}</button>)}</div><p className={styles.resultCount} role="status">{blocks.length} {blocks.length===1?"bloco encontrado":"blocos encontrados"}</p><section className={styles.grid}>{blocks.slice(0,36).map(({lesson,block})=><article key={`${lesson.id}-${block.id}`}><div><span>{lesson.ageBand} · {block.minutes} min</span><em>{block.screenMode==="off"?"sem ecrã":block.screenMode==="minimal"?"ecrã mínimo":"visual"}</em></div><h2>{block.title}</h2><p>{block.objective}</p><small>Dentro de: <strong>{lesson.title}</strong> · {lesson.repertoire}</small></article>)}</section>{!blocks.length&&<div className={styles.noResults}><strong>Nenhum bloco com estes filtros.</strong><button onClick={()=>{setQuery("");setAge("all");setKind("all")}}>Limpar filtros</button></div>}</div>;
}
