import type { ManualLessonGuide } from "@/lib/lesson-guides";
const g=(teach:string[],say:string,practice:string[],childDoes:string):ManualLessonGuide=>({teach,say,practice,childDoes});
export const guides58_2_12:Record<string,ManualLessonGuide>={
"5-8:2":g(["Mostre as duas mãos abertas e numere: polegar 1, indicador 2, médio 3, anelar 4, mindinho 5.","Diga números fora de ordem e peça que a criança levante o dedo sem tocar.","Pouse a mão direita relaxada em cinco teclas vizinhas.","Toque apenas 1–2–3 e depois 3–2–1; repita com a esquerda."],"O polegar é sempre 1. O mindinho é sempre 5. Vamos ver se os dedos respondem pelo nome.",["Faça 8 chamadas aleatórias entre 1 e 5, alternando as mãos.","Toque 1–2–3 | 3–2–1 com cada mão.","Termine com uma pequena pergunta numa mão e resposta na outra."],"Reconhece os cinco números nas duas mãos e usa 1–2–3 sem tensão."),
"5-8:3":g(["Mostre um grupo de duas pretas e um de três.","Peça que encontre outro grupo igual longe do primeiro.","Percorram o teclado apontando 2–3–2–3 sem contar teclas brancas.","Faça uma corrida lenta: professor aponta uma região, criança encontra 2 ou 3."],"O piano repete duas famílias: duas pretas e três pretas. Quando reconheces as famílias, o teclado deixa de parecer gigante.",["Faça 8 pedidos misturando grupo de 2 e de 3.","Mude de região em cada pedido.","Peça que a criança escolha um grupo e desafie o professor."],"Encontra grupos de duas e três pretas em qualquer região sem contar uma a uma."),
"5-8:4":g(["Encontre duas teclas pretas juntas.","Aponte a branca imediatamente à esquerda e diga Dó.","Repita o processo em quatro regiões.","Depois afaste as mãos e peça que a criança encontre os Dós sozinha."],"Sempre que encontrares duas pretas, o Dó está logo antes delas.",["Peça quatro Dós: grave, médio, outro médio e agudo.","Escolha um deles e toque Dó–Ré–Mi.","Feche os olhos e peça à criança que lhe mostre outro Dó."],"Localiza Dó pelo padrão de duas pretas sem etiquetas."),
"5-8:5":g(["Toque uma nota muito grave, uma média e uma muito aguda.","Peça que a criança aponte a região antes de dizer o nome.","Caminhe pelo teclado de grave para agudo tocando notas sucessivas.","Faça o caminho inverso e pergunte em que direção o som viajou."],"O piano tem bairros. À esquerda os sons ficam graves; à direita ficam agudos.",["Faça seis exemplos auditivos sem deixar a criança olhar.","Depois peça: grave, médio, agudo, em ordem aleatória.","Crie um caminho grave → médio → agudo e deixe a criança criar outro."],"Reconhece regiões e direção sonora pelo ouvido e pela posição."),
"5-8:6":g(["Escolha três teclas brancas vizinhas.","Toque a mesma tecla três vezes e diga 'repetiu'.","Toque três vizinhas para a direita e diga 'subiu'.","Faça o mesmo para a esquerda e diga 'desceu'."],"Antes de ler notas, vamos aprender a enxergar o desenho da música: repete, sobe ou desce.",["Toque seis padrões de três sons para a criança classificar.","Depois a criança toca um padrão de cada tipo.","Junte dois padrões numa frase de seis sons."],"Distingue repetição, subida e descida e consegue produzir cada padrão."),
"5-8:7":g(["Marche oito passos iguais sem piano.","Continue os passos e bata uma palma em cada um.","Sente ao piano e toque uma tecla por pulso.","Mostre a semínima somente depois de o pulso estar estável."],"O pulso é o passo da música. Ele não corre quando a nota muda.",["Conte 1–2–3–4 por quatro compassos.","Toque uma nota por pulso.","Depois use Dó–Ré–Mi–Ré mantendo exatamente o mesmo passo."],"Mantém pulsação regular enquanto muda de nota."),
"5-8:8":g(["Relembre rapidamente postura, Dó, dedos e pulso.","Toque a primeira frase da música conhecida do mês para a criança ouvir inteira.","Ensine apenas a primeira frase por imitação ou leitura adequada ao nível.","Acrescente a segunda frase e una as duas sem voltar ao início a cada erro."],"Hoje não é uma prova. Vamos mostrar a música que construímos durante o mês.",["Toque as frases separadamente uma vez.","Faça uma execução contínua da versão aprendida.","Repita apenas um trecho que realmente precise e faça uma última apresentação."],"Toca a versão mensal com começo, continuidade e final."),
"5-8:9":g(["Marque quatro pulsações com a mão.","Toque uma nota em cada pulso e mostre quatro semínimas.","Faça a criança contar e tocar ao mesmo tempo.","Troque as alturas sem mudar a duração."],"Semínima quer dizer: um som começa em cada pulso.",["Leia três compassos só com semínimas.","Depois use duas ou três alturas diferentes.","Faça uma rodada sem contar em voz alta, mantendo o pulso interno."],"Lê semínimas como um som por pulso sem acelerar."),
"5-8:10":g(["Toque uma nota e conte 1–2 sem repetir.","Mostre a mínima e compare visualmente com duas semínimas.","Faça quatro mínimas seguidas com contagem.","Aplique duas mínimas numa pequena frase."],"A mínima começa uma vez e fica viva durante dois pulsos.",["Alterne semínima–semínima–mínima.","Conte primeiro, depois toque.","Peça que a criança invente um compasso de quatro tempos usando as duas figuras."],"Sustenta mínimas por dois pulsos e combina-as com semínimas."),
"5-8:11":g(["Conte quatro pulsos continuamente.","No terceiro, não toque, mas mantenha a mão marcando o pulso.","Mostre a pausa correspondente ao valor trabalhado.","Repita até a entrada depois do silêncio acontecer no tempo."],"Silêncio não apaga o pulso. Continuamos a contar por dentro.",["Faça três padrões com uma pausa.","Bata primeiro e toque depois.","Peça que a criança crie um padrão com um silêncio e o professor copie."],"Mantém a contagem durante a pausa e volta no pulso correto."),
"5-8:12":g(["Toque uma nota e conte 1–2–3–4 sem repetir.","Mostre a semibreve e compare com quatro semínimas.","Faça a criança ouvir a ressonância até ao quarto pulso.","Use pedal apenas se for necessário para demonstrar sustentação, não como técnica ainda."],"Uma nota pode começar agora e continuar a soar enquanto quatro pulsos passam.",["Alterne uma semibreve com quatro semínimas.","Faça dois compassos em sequência.","Aplique uma nota longa no final de uma frase da música."],"Sustenta quatro pulsos sem repetir a tecla nem perder a contagem.")
};