import type { CurriculumVariant, EnhancedLesson, EnhancedModule } from "@/lib/curriculum-v3";
import type { AgeGroup } from "@/lib/curriculum";
import { lessonResourceSummary } from "@/lib/curriculum-resources";
import { getManualLessonGuide } from "@/lib/lesson-guides";
import { getCompletePreschoolLessonSteps } from "@/lib/preschool-lesson-map";

export type LessonStep = {
  id:string; icon:string; title:string; duration:string; goal:string;
  actions:string[]; say?:string; childDoes:string; success:string; tip?:string;
  actionLabel?:string; actionHref?:string; example?:string; songId?:string; songEmoji?:string; songStory?:string;
};

function firstLesson(age:AgeGroup):LessonStep[]{
  if(age==="2-4") return [
    {id:"warmup",icon:"👋",title:"Conhecer o piano",duration:"2–3 min",goal:"Fazer a criança sentir que o piano é um lugar seguro para explorar.",actions:["Fique ao lado do piano com a criança antes de sentá-la.","Aponte para as teclas e deixe a criança tocar livremente por 20–30 segundos.","Não corrija dedo, nota ou ritmo nesta primeira exploração."],say:"Hoje o piano vai falar com a gente. Pode tocar algumas teclas e descobrir os sons.",childDoes:"Explora algumas teclas livremente e escuta.",success:"Toca sem receio e mantém interesse por alguns segundos."},
    {id:"discover",icon:"🔎",title:"Um som grande e um som pequenino",duration:"4–5 min",goal:"Perceber que existem sons muito diferentes no mesmo piano.",actions:["Toque UMA tecla bem à esquerda.","Espere a criança escutar.","Toque UMA tecla bem à direita.","Repita esquerda → direita duas vezes.","Depois deixe a criança experimentar os dois lados."],say:"Este som parece grandão. E este parece pequenino. Agora faz tu.",childDoes:"Toca uma tecla do lado grave e depois uma do lado agudo.",success:"Experimenta os dois lados do piano, mesmo sem usar os nomes grave/agudo."},
    {id:"activity",icon:"🎮",title:"Onde mora o som?",duration:"3–4 min",goal:"Repetir a descoberta sem transformar a aula numa explicação.",actions:["Antes da aula, recorte as duas casas coloridas e os dois personagens em contorno.","Entregue o elefante e o passarinho para a criança colorir.","Coloque a CASA DO SOM GRANDÃO à esquerda do piano e a CASA DO SOM PEQUENINO à direita.","Toque um som bem grave e pergunte onde o personagem desse som deve morar.","A criança coloca o elefante na Casa do Som Grandão.","Toque um som bem agudo e repita a pergunta.","A criança coloca o passarinho na Casa do Som Pequenino.","Retire os personagens e faça mais 4 rodadas, alternando grave e agudo."],say:"Vamos descobrir onde cada amigo mora. Escuta primeiro e depois coloca-o na casa certa.",childDoes:"Colore os dois personagens, recorta com ajuda quando necessário e posiciona cada um na casa correspondente ao som.",success:"Associa elefante ao grave e passarinho ao agudo e escolhe a casa correta em pelo menos 3 de 4 rodadas.",tip:"KIT RECORTÁVEL: casas já coloridas + elefante e passarinho em preto e branco para colorir. Para 2–3 anos, o adulto faz o recorte; a criança apenas colore e posiciona.",actionLabel:"BAIXAR KIT RECORTÁVEL · A4",actionHref:"/printables/aula-1/casas-onde-mora-o-som.pdf"},
    {id:"repertoire",icon:"🎹",title:"Mini música: Gigante e Estrelinha",duration:"5–6 min",goal:"Terminar a primeira aula já fazendo música.",actions:["Escolha uma tecla branca grave para o Gigante.","Escolha uma tecla branca aguda para a Estrelinha.","Toque: Gigante – Gigante – Estrelinha – Estrelinha.","Peça para repetir os 4 sons.","Repitam juntos mais uma vez."],say:"O Gigante dá dois passos: TUM, TUM. A Estrelinha responde: TIM, TIM.",childDoes:"Toca 2 sons graves e 2 agudos como história.",success:"Completa a sequência com ajuda, sem precisar ficar perfeita."},
    {id:"create",icon:"✨",title:"Escolher o final",duration:"2 min",goal:"Dar sensação de autoria desde a primeira aula.",actions:["Toque novamente os quatro sons.","Pare antes do fim.","Deixe a criança escolher qualquer tecla como último som."],say:"Agora tu escolhes o último som.",childDoes:"Escolhe uma tecla para terminar.",success:"Faz uma escolha e percebe que ela muda a música."},
    {id:"close",icon:"🌟",title:"Fechar e celebrar",duration:"2 min",goal:"Encerrar com uma coisa que a criança conseguiu fazer.",actions:["Pergunte qual som gostou mais.","Toquem uma última sequência.","Elogie algo concreto: escuta, coragem ou atenção."],say:"Hoje tu descobriste dois lugares do piano e já fizeste uma música.",childDoes:"Repete a mini música uma última vez.",success:"Sai da aula associando o piano a descoberta e música.",tip:"Em casa: 2 sons graves + 2 agudos. Menos de 2 minutos."}
  ];
  return [
    {id:"warmup",icon:"🪑",title:"Sentar bem sem ficar rígido",duration:"3–4 min",goal:"Ajustar o corpo para tocar confortavelmente.",actions:["Sente o aluno no meio do teclado.","Ajuste a distância até os cotovelos ficarem ligeiramente à frente do tronco.","Verifique apoio dos pés.","Peça para soltar ombros e braços por 3 segundos."],say:"Quero que fiques confortável, não parado como uma estátua.",childDoes:"Ajusta banco, pés, ombros e braços.",success:"Alcança o teclado sem ombros levantados ou braços esticados."},
    {id:"discover",icon:"🖐️",title:"A mão pousa no teclado",duration:"5–6 min",goal:"Produzir os primeiros sons sem tensão.",actions:["Deixe a mão cair relaxada ao lado do corpo.","Leve a mesma forma até o teclado.","Coloque 1–2–3 sobre três teclas brancas vizinhas.","Peça um som com 1, depois 2, depois 3."],say:"Não aperta a mão. Só pousa e deixa cada dedo fazer um som.",childDoes:"Toca três teclas vizinhas com 1–2–3.",success:"Produz três sons sem travar pulso ou ombro."},
    {id:"activity",icon:"🎯",title:"Jogo dos três dedos",duration:"4–5 min",goal:"Reconhecer 1–2–3 e responder rapidamente.",actions:["Diga um número entre 1, 2 e 3.","O aluno toca uma vez com esse dedo.","Faça 6 chamadas aleatórias.","Depois faça duas chamadas juntas, como 1–2 ou 3–2."],say:"Quando eu disser o número, toca uma vez com esse dedo.",childDoes:"Responde aos números com o dedo correspondente.",success:"Acerta 5 de 6 chamadas simples sem tensão."},
    {id:"repertoire",icon:"🎹",title:"Primeira peça: Três Passos",duration:"10 min",goal:"Tocar uma peça curta na primeira aula.",actions:["Escolha três teclas brancas vizinhas para 1–2–3.","Ensine 1–2–3.","Depois 3–2–1.","Una: 1–2–3 | 3–2–1.","Repita 3 vezes devagar."],say:"Vamos subir três passos e voltar para casa.",childDoes:"Toca 1–2–3 | 3–2–1.",success:"Toca a sequência completa duas vezes sem perder a posição."},
    {id:"create",icon:"✨",title:"Mudar o final",duration:"3–4 min",goal:"Juntar técnica e criatividade.",actions:["Toque Três Passos novamente.","Na última nota, deixe escolher uma das três teclas.","Compare o final original com o novo."],say:"Muda só a última nota. Qual final gostas mais?",childDoes:"Escolhe outro final e toca novamente.",success:"Altera o final sem perder toda a sequência."},
    {id:"close",icon:"🌟",title:"Fechar a aula",duration:"2–3 min",goal:"Sair sabendo exatamente o que praticar.",actions:["Peça uma última execução.","Diga uma coisa específica que melhorou.","Mostre a tarefa: duas execuções em casa."],say:"Hoje já tens uma primeira peça. Em casa, toca duas vezes e para.",childDoes:"Faz uma execução final.",success:"Toca com postura funcional e sabe a tarefa.",tip:"Se houver tensão, marque “Precisa reforçar”; não bloqueie a aula seguinte."}
  ];
}

function warmup(age:AgeGroup,lesson:EnhancedLesson):LessonStep{
  if(age==="2-4"){
    const modes=[
      {title:"Acordar os ouvidos",icon:"👂",actions:["Feche os olhos com a criança por 5 segundos.","Faça dois sons contrastantes ligados ao tema da aula.","Peça apenas um gesto para cada som; não explique ainda."],say:"Escuta primeiro. O teu corpo vai mostrar o que ouviste.",child:"Escuta e responde com um gesto."},
      {title:"Corpo vira música",icon:"🕺",actions:["Escolha um movimento ligado ao foco da aula.","Faça o movimento quatro vezes com a criança.","Leve imediatamente o mesmo gesto para uma tecla ou região do piano."],say:"Faz comigo no corpo. Agora fazemos no piano.",child:"Imita o movimento e transfere a ideia para o piano."},
      {title:"Surpresa no piano",icon:"🎁",actions:["Cubra as mãos da criança ou peça que olhe para si.","Toque um exemplo curto do conceito do dia.","Pergunte o que ela percebeu sem exigir termos técnicos.","Deixe-a procurar uma resposta no teclado."],say:"Ouviste alguma coisa diferente? Mostra-me no piano.",child:"Escuta, escolhe e experimenta uma resposta."},
      {title:"Olá musical",icon:"👋",actions:["Cante o nome da criança em duas ou três pulsações.","Peça que responda o seu nome com palmas.","Repitam a resposta numa tecla confortável."],say:"Eu canto o teu nome; tu respondes com música.",child:"Responde com palmas e depois no piano."},
    ];
    const m=modes[(lesson.number-2)%modes.length];
    return {id:"warmup",icon:m.icon,title:m.title,duration:"2–3 min",goal:"Começar a aula brincando, ouvindo e mexendo o corpo.",actions:m.actions,say:m.say,childDoes:m.child,success:"Pode seguir quando a criança entra na brincadeira e tenta responder, mesmo que ainda copie o professor."};
  }
  return {id:"warmup",icon:"👋",title:"Aquecimento",duration:"3–5 min",goal:`Preparar corpo, pulso e atenção para ${lesson.focus.toLowerCase()}.`,actions:["Confira rapidamente postura e mãos.","Faça 8 pulsações com palmas.","Transfira as mesmas 8 pulsações para uma tecla confortável."],say:"Primeiro sentimos o pulso; depois levamos para o piano.",childDoes:"Mantém pulsação e transfere para o teclado.",success:"Começa a aula com corpo solto e pulso estável."};
}

function discovery(age:AgeGroup,lesson:EnhancedLesson):LessonStep{
  const guide=getManualLessonGuide(age,lesson.number);
  if(!guide) throw new Error(`Falta guia manual para ${age}:${lesson.number}`);
  return {id:"discover",icon:"🎯",title:"Vamos descobrir",duration:age==="2-4"?"4–6 min":"7–10 min",goal:age==="2-4"?`Hoje a criança vai brincar com ${lesson.title.toLowerCase()}.`:lesson.objective,actions:guide.teach,say:guide.say,childDoes:guide.childDoes,success:lesson.mastery};
}

function activity(age:AgeGroup,lesson:EnhancedLesson,game?:{title:string;goal:string;session:string},href?:string):LessonStep{
  const guide=getManualLessonGuide(age,lesson.number);
  if(!guide) throw new Error(`Falta guia manual para ${age}:${lesson.number}`);
  if(game&&href) return age==="2-4"
    ? {id:"activity",icon:"🎮",title:game.title,duration:"3–5 min",goal:"Brincar com a descoberta de hoje sem transformar o jogo numa prova.",actions:["Abra o jogo e faça a primeira brincadeira junto com a criança.","Na próxima, espere um pouco e deixe a criança escolher primeiro.","Se ela errar, mostre de novo brincando; não peça para repetir até acertar.","Depois de poucas rodadas, feche o jogo e volte ao piano."],say:"Agora és tu! Escuta ou olha... e escolhe.",childDoes:"Joga, escolhe e experimenta sem precisar acertar tudo.",success:"Pode seguir quando a criança já percebe a brincadeira e começa a escolher com menos ajuda.",actionLabel:"ABRIR JOGO",actionHref:href}
    : {id:"activity",icon:"🎮",title:game.title,duration:"5–7 min",goal:game.goal,actions:["Abra o jogo e faça uma rodada de demonstração.","Na rodada seguinte, deixe a criança responder primeiro.","Faça apenas a sessão indicada; não repita até acertar tudo.","Volte para o piano físico ao terminar."],say:"Agora és tu. Primeiro escuta ou olha; depois escolhe.",childDoes:`Completa uma sessão curta de ${game.session}.`,success:"Entende a regra e responde à maior parte sem ajuda constante.",actionLabel:"ABRIR JOGO",actionHref:href};
  return {id:"activity",icon:"🧩",title:age==="2-4"?`Vamos brincar: ${lesson.title}`:"Praticar a habilidade",duration:age==="2-4"?"3–5 min":"5–7 min",goal:age==="2-4"?"Brincar mais uma vez com o que acabou de descobrir.":`Usar ${lesson.focus.toLowerCase()} numa tarefa concreta, sem acrescentar teoria nova.`,actions:guide.practice,say:guide.say,childDoes:guide.childDoes,success:age==="2-4"?"Pode seguir quando a criança tenta a brincadeira e já precisa de menos ajuda para saber o que fazer.":"Consegue repetir a proposta com menos ajuda do que na primeira demonstração."};
}

function repertoire(age:AgeGroup,lesson:EnhancedLesson,songHref?:string):LessonStep{
  if(age==="2-4") return {id:"repertoire",icon:"🎹",title:`Hora da música: ${lesson.repertoire}`,duration:"5–8 min",goal:"Usar a descoberta de hoje dentro de uma música de verdade.",actions:["Ouça ou toque um pedacinho curto primeiro.","Convide a criança a cantar, mexer o corpo ou fazer o gesto da música.","Mostre no piano apenas a parte que ela consegue experimentar hoje.","Toquem juntos sem parar a cada erro.","Termine enquanto a criança ainda quer brincar com a música."],say:`Agora ${lesson.repertoire} vai brincar com a gente. Primeiro ouvimos; depois tocamos juntos.`,childDoes:"Ouve, participa da história da música e toca um pequeno pedaço no piano.",success:"Pode seguir quando a criança participa da música e consegue experimentar pelo menos um pedacinho, com ajuda se precisar.",tip:"Nesta idade, a música não é uma prova. Ouvir, cantar, mover e tocar também contam como aprender.",actionLabel:songHref?"OUVIR / TOCAR MÚSICA":"VER MÚSICAS",actionHref:songHref??"/musicas"};
  return {id:"repertoire",icon:"🎹",title:"Música no piano",duration:"10–15 min",goal:`Aplicar a aula em ${lesson.repertoire}.`,actions:["Escolha se a prática será no Luwipi ou no piano físico.","Trabalhe apenas UMA frase de cada vez.","Faça uma demonstração curta e depois deixe a criança tocar.","Junte duas frases somente quando a primeira estiver confortável.","No final, faça uma tentativa contínua sem parar para corrigir cada erro."],say:`Vamos tocar ${lesson.repertoire} por partes. Primeiro uma frase; depois juntamos.`,childDoes:"Toca uma frase, repete e junta as partes gradualmente.",success:"Consegue completar pelo menos uma frase com começo e fim claros.",tip:"Se escolher piano físico, use o modo “Piano físico” da música: ele mostra onde começar e a sequência da frase.",actionLabel:songHref?"ABRIR MÚSICA":"ABRIR REPERTÓRIO",actionHref:songHref??"/musicas"};
}

function creation(age:AgeGroup,lesson:EnhancedLesson):LessonStep{
  if(lesson.checkpoint) return age==="2-4"
    ? {id:"checkpoint",icon:"🏁",title:"Festa Luwipi",duration:"3–5 min",goal:"Reencontrar brincadeiras conhecidas e celebrar o que a criança já faz.",actions:["Escolha uma brincadeira de ouvir que ela já conhece.","Faça uma brincadeira curta de ritmo ou movimento.","Peça para encontrar alguma coisa conhecida no piano.","Termine com um pedacinho de uma música favorita."],say:"Hoje vamos brincar outra vez com algumas coisas que já conheces. Tu escolhes uma também!",childDoes:"Revê brincadeiras conhecidas, escolhe e participa.",success:"Pode seguir quando a criança reconhece algumas brincadeiras e entra nelas com vontade, mesmo que ainda precise de ajuda."}
    : {id:"checkpoint",icon:"🏁",title:"Missão Luwipi",duration:"5–8 min",goal:"Ver o que já está seguro e o que vale reforçar.",actions:["Faça 1 desafio de ouvido.","Faça 1 de ritmo.","Faça 1 de teclado ou leitura.","Peça um pequeno trecho de repertório.","Registre apenas uma coisa para reforçar."],say:"São quatro missões rápidas. Não é prova.",childDoes:"Resolve quatro pequenos desafios.",success:"Mostra o que consegue sem ajuda constante e identifica um próximo foco."};
  if(age==="2-4"){
    const mode=lesson.number%5;
    if(mode===0) return {id:"create",icon:"🎭",title:"Dar voz a um personagem",duration:"2–4 min",goal:"Transformar a habilidade em imaginação.",actions:["Peça à criança para escolher um personagem.","Pergunte como esse personagem soaria no piano.","Deixe-a tocar a resposta.","Imite a ideia dela uma vez."],say:"Como este personagem fala no piano?",childDoes:"Escolhe um som para representar um personagem.",success:"Liga uma escolha sonora a uma intenção própria."};
    if(mode===1) return {id:"create",icon:"🧩",title:"Completar a música",duration:"2–4 min",goal:"Antecipar e escolher um final.",actions:["Toque uma sequência curta usando a habilidade do dia.","Pare antes do último som.","Deixe a criança escolher o final.","Repita com um final diferente."],say:"A música parou! Que som falta no final?",childDoes:"Escolhe dois finais possíveis.",success:"Faz uma escolha musical sem esperar uma única resposta certa."};
    if(mode===2) return {id:"create",icon:"🎨",title:"Pintar com sons",duration:"2–4 min",goal:"Explorar contraste e intenção.",actions:["Diga uma imagem simples: chuva, gigante, passarinho ou vento.","A criança escolhe como fazê-la soar.","Faça uma segunda imagem contrastante.","Juntem as duas numa mini história."],say:"Mostra-me esta imagem usando só o piano.",childDoes:"Cria dois sons contrastantes e junta-os.",success:"Usa o piano para representar duas ideias diferentes."};
    if(mode===3) return {id:"create",icon:"🔁",title:"Trocar de papel",duration:"2–4 min",goal:"Dar liderança musical à criança.",actions:["A criança toca uma ideia de 1 a 3 sons.","O professor imita exatamente.","Troquem novamente os papéis.","Na última rodada, a criança decide quando termina."],say:"Agora tu és o professor. Eu vou copiar.",childDoes:"Cria um padrão curto para o professor imitar.",success:"Lidera pelo menos uma rodada com intenção."};
    return {id:"create",icon:"🪄",title:"Mudar uma coisa",duration:"2–4 min",goal:"Perceber que pequenas escolhas transformam a música.",actions:["Repita a atividade principal uma vez.","Peça para mudar apenas uma coisa: lado, força, velocidade, dedo ou final.","Toquem a versão nova.","Pergunte qual das duas prefere."],say:"Vamos mudar só uma coisa e ouvir o que acontece.",childDoes:"Altera um elemento e compara as duas versões.",success:"Consegue mudar deliberadamente um elemento musical."};
  }
  return {id:"create",icon:"✨",title:"Criar e responder",duration:"4–6 min",goal:"Usar a habilidade do dia de forma livre.",actions:["Toque uma frase curta.","Peça uma resposta.","Aceite a primeira resposta musicalmente possível.","Repita a pergunta e peça uma segunda resposta diferente."],say:"Eu faço uma pergunta; tu inventas a resposta.",childDoes:"Cria duas respostas curtas.",success:"Faz escolhas próprias sem esperar uma nota certa."};
}

function close(age:AgeGroup,lesson:EnhancedLesson,homeworkHref:string):LessonStep{
  return age==="2-4"
    ? {id:"close",icon:"🌟",title:"Tchau, piano!",duration:"2–3 min",goal:"Terminar feliz e deixar uma lembrança simples da brincadeira de hoje.",actions:["Peça para a criança escolher uma coisa que quer fazer mais uma vez.","Repitam essa brincadeira ou som uma única vez.","Diga exatamente uma coisa bonita que ela conseguiu hoje.","Mostre ao adulto a brincadeira curtinha que pode repetir em casa."],say:"Qual foi a tua parte favorita? Vamos fazer só mais uma vez e dizer tchau ao piano.",childDoes:"Escolhe uma parte favorita, repete e termina a aula.",success:lesson.mastery,tip:`Em casa: ${lesson.homePractice}`,actionLabel:"VER BRINCADEIRA DE CASA",actionHref:homeworkHref}
    : {id:"close",icon:"🌟",title:"Fechar a aula",duration:"2–3 min",goal:"Sair sabendo o que conseguiu e o que fará em casa.",actions:["Peça uma última tentativa curta.","Escolha “Conseguiu” ou “Precisa reforçar”.","Diga UMA tarefa para casa.","Pare a aula; não acrescente exercício novo no final."],say:"Hoje o foco foi este. Em casa pratica só o trecho combinado e depois toca a peça uma vez.",childDoes:"Faz uma tentativa final e ouve a tarefa.",success:lesson.mastery,tip:`Tarefa: ${lesson.homePractice}`,actionLabel:"PREPARAR TAREFA",actionHref:homeworkHref};
}

export function buildLessonSteps(args:{age:AgeGroup;module:EnhancedModule;lesson:EnhancedLesson;variant:CurriculumVariant;}):LessonStep[]{
  const {age,lesson}=args;
  const resources=lessonResourceSummary(age,lesson.number,lesson.repertoire);
  if(age==="2-4"){
    const preschool=getCompletePreschoolLessonSteps(lesson.number);
    if(!preschool) throw new Error(`Falta experiência infantil individual para a aula ${lesson.number}`);
    return preschool;
  }
  if(lesson.number===1) return firstLesson(age);
  const href=resources.gameHref??lesson.activityRoute;
  return [warmup(age,lesson),discovery(age,lesson),activity(age,lesson,resources.game,href),repertoire(age,lesson,resources.songHref),creation(age,lesson),close(age,lesson,resources.homeworkHref)];
}
