import type { ManualLessonGuide } from "@/lib/lesson-guides";
const g=(teach:string[],say:string,practice:string[],childDoes:string):ManualLessonGuide=>({teach,say,practice,childDoes});
export const guides58_2_12:Record<string,ManualLessonGuide>={
"5-8:2":g(["Mostre as duas mãos e diga: polegar 1, indicador 2, médio 3, anelar 4, mindinho 5.","Peça: 'mostra o 2', 'mostra o 5', alternando mãos sem piano.","Pouse a mão direita relaxada em cinco teclas vizinhas e toque 1–2–3 | 3–2–1.","Repita com a esquerda, sem exigir força igual em todos os dedos."],"O número pertence ao dedo, não à tecla. Polegar é 1 nas duas mãos.",["Faça 8 chamadas aleatórias de dedos.","Toque 1–2–3 | 3–2–1 com cada mão.","A criança cria uma sequência de três números e toca."],"Identifica dedos 1–5 nas duas mãos e usa uma sequência curta sem tensão."),
"5-8:3":g(["Mostre um grupo de duas pretas e outro de três.","Percorra o teclado dizendo apenas '2, 3, 2, 3'.","Pare em regiões diferentes e peça que encontre a família pedida.","Peça que a criança escolha uma família e desafie o professor."],"O teclado parece enorme, mas repete sempre duas famílias: duas pretas e três pretas.",["Faça 8 pedidos alternando grupos de 2 e 3.","Mude de região a cada pedido.","Termine encontrando três grupos sem olhar para as mãos do professor."],"Encontra grupos de duas e três pretas rapidamente em regiões diferentes."),
"5-8:4":g(["Encontre duas teclas pretas juntas.","Mostre a branca imediatamente à esquerda: esse é Dó.","Repita em quatro regiões sem colocar etiquetas.","Afaste-se e peça que encontre um Dó grave, um médio e um agudo."],"Duas pretas são a pista. O Dó mora logo antes delas.",["Faça uma caça a cinco Dós.","Toque Dó–Ré–Mi a partir de um deles.","Peça à criança que ensine ao professor como encontrar Dó."],"Encontra Dó pelo padrão de duas pretas sem decorar posições isoladas."),
"5-8:5":g(["Toque uma nota bem grave, uma média e uma bem aguda.","A criança aponta a região antes de ouvir os nomes.","Faça um caminho de três sons indo para a direita e outro para a esquerda.","Associe direita a som que sobe e esquerda a som que desce."],"À esquerda o piano fica mais grave; à direita fica mais agudo. O som também pode viajar.",["Faça seis exemplos auditivos com a criança sem olhar.","Peça grave, médio e agudo em ordem aleatória.","A criança cria um caminho e o professor diz se subiu ou desceu."],"Reconhece regiões e direção sonora pelo ouvido e pelo teclado."),
"5-8:6":g(["Escolha três teclas vizinhas.","Toque Dó–Dó–Dó: repetiu.","Toque Dó–Ré–Mi: subiu.","Toque Mi–Ré–Dó: desceu.","Misture os três desenhos sem nomear as notas primeiro."],"Antes de ler nomes, conseguimos ler o caminho: repetiu, subiu ou desceu.",["Classifique seis padrões de três sons.","A criança toca um exemplo de cada tipo.","Una dois padrões numa frase de seis sons."],"Reconhece e produz repetição, subida e descida."),
"5-8:7":g(["Marche oito passos iguais.","Continue os passos e bata uma palma em cada um.","Sente ao piano e toque uma tecla por passo.","Troque a tecla sem deixar o pulso correr."],"O pulso é o passo da música. As notas mudam, mas o passo continua.",["Conte quatro grupos de 1–2–3–4.","Toque Dó–Ré–Mi–Ré mantendo o mesmo pulso.","Professor para de contar; criança mantém mais oito pulsos."],"Mantém pulsação regular enquanto muda de nota."),
"5-8:8":g(["Cante ou toque a música conhecida do mês inteira.","Peça que a criança mostre a primeira frase que já aprendeu.","Trabalhe somente o pedaço seguinte que falta.","Una as partes e faça uma execução contínua."],"Hoje vamos tocar a música do mês como música: começo, caminho e final.",["Toque cada trecho uma vez.","Corrija somente o ponto que impede a continuidade.","Faça uma apresentação completa sem parar por pequenos erros."],"Toca a versão aprendida do repertório do mês com começo e final claros."),
"5-8:9":g(["Marque quatro pulsos com a mão.","Toque um som em cada pulso e só então mostre quatro semínimas.","Conte e toque juntos.","Troque as alturas sem mudar o espaço entre os ataques."],"Cada semínima começa em um pulso. Não precisamos correr porque a nota mudou.",["Leia três compassos de semínimas.","Use duas ou três alturas.","Faça uma rodada sem contar em voz alta."],"Lê semínimas como um som por pulso."),
"5-8:10":g(["Toque uma nota e conte 1–2 sem repetir.","Mostre a mínima e compare-a com duas semínimas.","Faça quatro mínimas seguidas.","Misture semínima–semínima–mínima."],"A mínima começa uma vez e continua viva durante dois pulsos.",["Conte antes de tocar dois padrões.","Toque semínima–semínima–mínima quatro vezes.","A criança monta um compasso de quatro pulsos com as duas figuras."],"Sustenta mínimas por dois pulsos e combina-as com semínimas."),
"5-8:11":g(["Conte quatro pulsos continuamente.","No terceiro, não toque, mas continue a marcar o pulso.","Mostre a pausa correspondente.","Repita até a entrada depois do silêncio acontecer no tempo certo."],"Silêncio também ocupa tempo. O pulso continua mesmo quando ninguém toca.",["Faça três padrões com uma pausa.","Bata primeiro e toque depois.","A criança cria um padrão com silêncio para o professor copiar."],"Mantém o pulso durante a pausa e regressa no momento correto."),
"5-8:12":g(["Toque uma nota e conte 1–2–3–4 sem repetir.","Mostre a semibreve e compare com quatro semínimas.","Ouçam a ressonância enquanto os quatro pulsos passam.","Use a nota longa como final de uma frase."],"A semibreve começa uma vez e ocupa quatro pulsos inteiros.",["Alterne uma semibreve e quatro semínimas.","Faça dois compassos seguidos.","Termine uma frase do repertório com uma nota de quatro pulsos."],"Sustenta quatro pulsos sem repetir nem perder a contagem.")
};