import type { ManualLessonGuide } from "@/lib/lesson-guides";
const g=(teach:string[],say:string,practice:string[],childDoes:string):ManualLessonGuide=>({teach,say,practice,childDoes});
export const guides58_13_24:Record<string,ManualLessonGuide>={
"5-8:13":g(["Marque um pulso lento.","Diga 'ta-ka' duas vezes dentro de cada pulso.","Troque a fala por duas palmas iguais.","Mostre o par de colcheias e toque duas vezes na mesma tecla por pulso."],"O pulso não ficou mais rápido. Agora colocamos dois sons dentro dele.",["Alterne um pulso de semínima e outro com duas colcheias.","Faça falar → bater → tocar.","Use Dó–Ré em pares sem acelerar."],"Executa pares de colcheias dentro de pulsação estável."),
"5-8:14":g(["Desenhe quatro espaços e conte 1–2–3–4.","Toque um som por pulso com leve apoio no 1.","Mostre 4/4 e diga apenas que cada compasso recebe quatro pulsos.","Preencha um compasso com figuras já conhecidas."],"Um compasso de 4/4 é uma caixa com quatro pulsos. Encheu quatro, começa outra.",["Monte três compassos.","Conte e bata antes de tocar.","A criança verifica se cada compasso soma quatro pulsos."],"Organiza figuras conhecidas em 4/4 e sente o primeiro pulso."),
"5-8:15":g(["Caminhe 1–2–3 repetidamente.","Dê leve apoio ao 1.","Compare com quatro passos de 4/4.","Toque uma nota grave no 1 e duas leves no 2–3."],"Em 3/4 a caixa termina no três: UM–dois–três.",["Alterne exemplos de 3/4 e 4/4.","Toque três compassos em 3/4.","Faça uma mini valsa grave–leve–leve."],"Distingue 3/4 de 4/4 e mantém grupos de três."),
"5-8:16":g(["Escolha um ritmo de quatro pulsos.","Fale o ritmo, bata e só depois toque.","Use duas alturas para transformar o ritmo em frase.","Mostre um padrão parecido dentro do repertório do mês."],"Ritmo não fica sozinho no papel. Vamos fazê-lo virar música.",["Monte três ritmos curtos.","Faça falar → bater → tocar.","Escolha um e use-o numa frase de quatro compassos."],"Lê e executa combinações rítmicas sem perder o pulso."),
"5-8:17":g(["Mostre uma pauta sem nomes de notas.","Aponte linha–espaço–linha subindo e toque três teclas vizinhas para a direita.","Faça o mesmo descendo.","Mostre duas notas na mesma posição e compare com repetição no teclado."],"A pauta é um mapa: o desenho sobe, desce ou fica no mesmo lugar.",["Classifique seis desenhos.","Trace cada caminho com o dedo antes de tocar.","A criança desenha um caminho simples e transforma-o em som."],"Relaciona direção visual da pauta com direção no teclado."),
"5-8:18":g(["Encontre o Dó central pelo grupo de duas pretas.","Mostre o Dó central entre as duas pautas.","Toque o Dó e dois vizinhos acima e abaixo.","Volte ao Dó antes de cada pequeno caminho."],"Este Dó fica no centro do nosso mapa e ajuda a encontrar os vizinhos.",["Faça cinco retornos ao Dó central.","Leia padrões que começam nele.","Não escreva nomes das notas sobre a pauta."],"Encontra o Dó central no teclado e na pauta e usa-o como referência."),
"5-8:19":g(["Mostre a clave de Sol e a linha do Sol de referência.","Encontre esse Sol no teclado.","Mostre uma nota um passo acima e outra abaixo.","Peça primeiro direção/distância, depois a tecla."],"Conhecemos um lugar seguro: o Sol. A partir dele caminhamos.",["Leia seis notas próximas do Sol.","Diga primeiro sobe/desce e depois encontre a tecla.","Leia uma frase curta usando o Sol como âncora."],"Usa Sol como referência para ler notas próximas."),
"5-8:20":g(["Mostre a clave de Fá e o Fá de referência.","Encontre esse Fá na região da mão esquerda.","Mostre vizinhos acima e abaixo.","Relacione-o ao Dó central já conhecido."],"A clave de Fá mostra a região onde a mão esquerda vai trabalhar muito.",["Leia seis notas próximas do Fá.","Toque três padrões curtos.","Localize o Fá novamente sem ajuda."],"Usa Fá como referência inicial na clave de Fá."),
"5-8:21":g(["Mostre três desenhos: repetição, passo e salto.","A criança descreve o desenho antes de nomear notas.","Toque os três e compare pelo ouvido.","Encontre os mesmos padrões numa frase de partitura."],"Antes de perguntar 'qual nota?', pergunta: repetiu, andou ou saltou?",["Classifique oito padrões.","Toque quatro a partir de uma referência conhecida.","Encontre um passo e um salto no repertório."],"Reconhece repetição, passo e salto antes de nomear cada nota."),
"5-8:22":g(["Mostre uma frase de 4–6 notas.","Encontre somente a primeira nota por Dó, Sol ou Fá.","Leia o caminho inteiro com o dedo.","Só depois toque."],"Primeiro lemos o caminho. Depois colocamos a mão no piano.",["Faça quatro frases usando olhar → referência → padrão → tocar.","Não escreva letras na pauta.","Repita somente a frase em que a leitura quebrou."],"Lê frase curta por referência e padrão sem escrever nomes."),
"5-8:23":g(["Mostre Sol em cima e Fá em baixo.","Marque o Dó central entre as pautas.","Aponte uma nota e pergunte primeiro qual mão/região.","Alterne direita e esquerda em notas isoladas."],"Não são dois mapas. É o mesmo piano desenhado em duas pautas.",["Faça oito apontamentos rápidos.","Leia dois compassos alternando as mãos.","Volte ao Dó central como referência comum."],"Relaciona as duas claves sem perder a orientação."),
"5-8:24":g(["Abra a partitura simples da música do mês.","Antes de tocar, encontre compasso, primeira nota e padrões repetidos.","Leia a primeira frase com o dedo e toque.","Faça o mesmo com a segunda e una."],"A partitura mostra o caminho de uma música que os teus ouvidos já conhecem.",["Leia duas frases separadas.","Una sem parar a cada erro.","Faça uma execução contínua da versão aprendida."],"Usa a partitura como guia para tocar o repertório do mês.")
};