import type { ManualLessonGuide } from "@/lib/lesson-guides";
const g=(teach:string[],say:string,practice:string[],childDoes:string):ManualLessonGuide=>({teach,say,practice,childDoes});
export const guides58_25_36:Record<string,ManualLessonGuide>={
"5-8:25":g(["Pouse cinco dedos em cinco teclas vizinhas sem esticar.","Toque 1–2–3–4–5 e volte lentamente.","Observe ombro, pulso e articulações; pare se a mão torcer.","Repita na outra mão em região confortável."],"Cinco dedos, cinco teclas. A mão continua macia.",["Faça duas subidas e descidas em cada mão.","Mude a dinâmica sem mudar a forma.","Use o padrão numa frase curta."],"Toca pentacorde com cada mão mantendo conforto e pulso."),
"5-8:26":g(["Escolha cinco teclas para a mão direita.","Ensine uma frase curta com subida, repetição e final.","Cante a frase antes de tocar.","Toque inteira sem interromper cada nota."],"A mão direita vai contar uma frase, não uma lista de notas.",["Toque a frase duas vezes.","Na terceira, faça-a mais suave ou mais forte.","A criança mostra onde sente o final."],"Toca frase curta de mão direita com continuidade."),
"5-8:27":g(["Crie uma resposta de duas ou três notas para a esquerda.","Leia o desenho antes de tocar.","Use o mesmo pulso da pergunta da direita.","Faça pergunta MD → resposta ME."],"A esquerda responde no mesmo pulso; ela não chega atrasada.",["Faça quatro conversas MD → ME.","Troque a resposta uma vez.","Elimine a pausa extra entre as mãos."],"Toca resposta simples de mão esquerda mantendo o pulso."),
"5-8:28":g(["Toque três notas separadas e depois ligadas.","Mostre o dedo seguinte recebendo o peso antes do anterior sair.","Faça 1–2–3 e 3–2–1.","Aplique numa frase curta."],"Legato é passar o som de um dedo para o outro sem buraco e sem apertar.",["Faça três grupos de três notas ligadas.","Compare com uma versão separada.","Toque uma frase inteira em legato."],"Liga notas com transferência confortável entre os dedos."),
"5-8:29":g(["Toque três notas curtas com movimento pequeno e elástico.","Não deixe o punho endurecer nem os dedos puxarem para cima.","Compare staccato e legato nas mesmas notas.","Use staccato numa figura curta."],"Staccato é curto e leve. Não é bater.",["Alterne cartões 'ligado' e 'saltitante'.","Toque a mesma frase das duas formas.","Faça quatro compassos em staccato mantendo o pulso."],"Produz staccato leve sem tensão."),
"5-8:30":g(["Toque uma frase com a direita.","A esquerda responde no pulso seguinte.","Conte continuamente para evitar um buraco entre as mãos.","Reduza para duas notas se a troca ficar difícil."],"Uma mão termina e a outra continua a conversa.",["Faça seis trocas MD ↔ ME.","Mude a última resposta.","Aplique a alternância num trecho musical."],"Alterna frases entre as mãos sem quebrar o pulso."),
"5-8:31":g(["Segure uma nota longa com a esquerda.","Enquanto ela continua, toque 2–3 notas na direita.","Treine cada mão uma vez separada.","Junte um compasso e relaxe."],"Uma mão fica; a outra anda. Esse é o primeiro encontro das duas.",["Faça dois compassos com nota longa na esquerda.","Troque a nota-base.","Una quatro compassos se estiver confortável."],"Mantém uma mão sustentada enquanto a outra toca uma frase."),
"5-8:32":g(["Pegue a música conhecida do mês.","Marque exatamente onde a esquerda entra.","Treine apenas essas entradas.","Acrescente a direita em blocos de um compasso e una."],"Hoje as duas mãos entram numa música que já conhecemos.",["Toque separadamente só os pontos difíceis.","Una duas frases.","Faça uma execução contínua."],"Aplica coordenação inicial das duas mãos no repertório."),
"5-8:33":g(["Para 5–6, use Dó–Ré–Mi–Fá–Sol e volte.","Para 7–8, se a mão estiver pronta, introduza uma oitava de Dó maior.","Isole a passagem do polegar lentamente; se houver tensão, volte ao pentacorde.","Faça apenas duas tentativas boas."],"A escada tem de ficar suave. Se a mão aperta, encurtamos a escada.",["Escolha pentacorde ou oitava conforme a criança.","Faça duas tentativas lentas.","Use um fragmento numa pequena frase."],"Executa a versão adequada de Dó maior sem tensão."),
"5-8:34":g(["Toque Dó–Ré e conte 2ª.","A partir do mesmo Dó, mostre 3ª, 4ª e 5ª.","Veja a forma no teclado e na pauta.","Toque os intervalos melodicamente para ouvir o tamanho do salto."],"Intervalo é a distância entre duas notas.",["Faça oito exemplos de 2ª a 5ª.","A criança identifica antes de tocar.","Encontre dois intervalos no repertório."],"Reconhece 2ª a 5ª por forma, distância e som."),
"5-8:35":g(["Construa Dó–Mi–Sol.","Mostre: usa uma nota, salta uma, usa outra, salta uma, usa a terceira.","Toque juntas e depois separadas.","Mova o mesmo desenho apenas como exploração."],"Três notas organizadas assim formam uma tríade.",["Monte três tríades simples.","Toque quebradas e juntas.","Volte a Dó maior e reconheça a forma."],"Constrói uma tríade simples e reconhece sua organização."),
"5-8:36":g(["Construa C: Dó–Mi–Sol, F: Fá–Lá–Dó e G: Sol–Si–Ré.","Ouça cada acorde antes de trocar.","Faça C–F–G–C lentamente.","Se a mão for pequena, use nota-base ou duas notas em vez de forçar a tríade."],"C, F e G aparecem juntos em muitas músicas. Vamos aprender o caminho entre eles.",["Faça C–F–G–C quatro vezes sem correr.","Peça acordes em ordem aleatória.","Termine acompanhando quatro compassos simples."],"Encontra C, F e G em versão confortável e troca entre eles.")
};