import type { ManualLessonGuide } from "@/lib/lesson-guides";
const g=(teach:string[],say:string,practice:string[],childDoes:string):ManualLessonGuide=>({teach,say,practice,childDoes});
export const guides58_37_48:Record<string,ManualLessonGuide>={
"5-8:37":g(["Toque a mesma frase primeiro piano e depois forte.","Mostre p e f.","Faça crescendo em 4–8 notas sem acelerar.","A criança escolhe onde uma frase cresce e onde fica suave."],"Dinâmica muda a voz da música. Forte não significa bater.",["Toque duas frases com contraste p/f.","Faça um crescendo claro.","Aplique ao repertório."],"Controla intensidade sem perder qualidade do som."),
"5-8:38":g(["Toque uma frase sem direção e depois conduzindo até um ponto de chegada.","Pergunte qual parece contar melhor a história.","Marque o fim de duas frases.","Cante e depois toque se necessário."],"Uma frase musical também respira e vai a algum lugar.",["Toque duas frases com começo, direção e fim.","Faça pequena liberação no final.","Evite dar o mesmo peso a todas as notas."],"Toca frases com direção e final perceptíveis."),
"5-8:39":g(["Escolha melodia conhecida curta.","Toque a melodia sozinha.","Na esquerda, use primeiro uma nota-base no início do compasso.","Só depois experimente C, F ou G onde couber."],"A esquerda apoia a música; não precisa ficar ocupada o tempo todo.",["Faça quatro compassos com notas-base.","Passe para acordes somente onde estiver seguro.","Junte em andamento confortável."],"Acompanha melodia com base ou acordes simples sem perder o pulso."),
"5-8:40":g(["Toque a música conhecida do mês inteira.","Escolha duas decisões expressivas, como frase suave e crescendo.","Trabalhe somente o ponto em que técnica ou acompanhamento atrapalha.","Faça nova execução sem parar."],"Já conhecemos as notas. Agora fazemos a peça soar como música.",["Toque uma vez e escolha um ponto para melhorar.","Trabalhe-o por poucos minutos.","Toque novamente do início ao fim."],"Integra técnica, dinâmica e fraseado numa execução contínua."),
"5-8:41":g(["Toque três notas sem deixar a criança ver as mãos.","Espere dois segundos antes da resposta.","Repita uma segunda vez apenas se necessário.","Passe para quatro notas só quando três estiverem confortáveis."],"Guarda o som na cabeça primeiro. Depois procura no piano.",["Faça cinco ecos de três notas.","Troque os papéis.","Repita o eco mais difícil no final."],"Reproduz pequenas frases pelo ouvido sem depender da visão."),
"5-8:42":g(["Toque uma pergunta de quatro pulsos.","Deixe quatro pulsos para a resposta.","Mostre que a resposta não precisa copiar.","Troque os papéis."],"Não precisas copiar. A tua música só precisa responder à minha.",["Faça quatro perguntas e respostas.","Mantenha o mesmo tamanho das frases.","A criança faz a última pergunta."],"Cria respostas curtas com pulso e intenção."),
"5-8:43":g(["Escolha cinco teclas pretas ou cinco notas conhecidas.","Defina quatro pulsos por frase.","Improvisa uma frase e deixe quatro pulsos de espaço.","Mostre como repetir uma pequena ideia dá unidade."],"Aqui não procuramos a nota certa; procuramos uma frase com começo e fim.",["Crie quatro frases.","Repita um motivo em pelo menos duas.","Professor pode acompanhar com base simples."],"Improvisa dentro de limites simples mantendo frase e pulso."),
"5-8:44":g(["Peça uma ideia de 2–4 notas.","Use-a no compasso 1.","No 2, repita ou mude uma coisa.","No 3, faça contraste; no 4, crie final.","Registre com notação adequada ao nível."],"Quatro compassos podem contar uma história: ideia, volta, surpresa e final.",["Toque os quatro compassos.","Mude só um elemento se necessário.","Dê um título e toque completa."],"Organiza e repete composição curta de quatro compassos."),
"5-8:45":g(["Escolha 1–2 compassos que falham.","Descubra se o problema é nota, dedo, ritmo ou troca de mão.","Reduza o andamento e resolva só esse problema.","Faça três repetições corretas e recoloque na frase."],"Não repetimos a peça inteira para consertar dois compassos.",["Trabalhe dois trechos separadamente.","Faça no máximo três repetições corretas seguidas.","Toque a peça inteira uma vez."],"Sabe isolar um problema e reintegrá-lo na música."),
"5-8:46":g(["Combine antes: não voltar ao início por erro pequeno.","Faça execução completa em andamento confortável.","Se falhar, continue no pulso ou salte ao próximo ponto conhecido.","Corrija apenas depois de terminar."],"Num concerto a música continua. Recuperar também é saber tocar.",["Faça duas execuções completas.","Entre elas, corrija um ponto.","Compare qual teve melhor continuidade."],"Mantém a peça fluindo e recupera pequenos erros."),
"5-8:47":g(["Grave uma execução completa.","Escute sem interromper.","A criança escolhe uma coisa boa e uma para melhorar.","Trabalhe só esse ponto e grave novamente."],"Não vamos caçar erros. Vamos ouvir uma melhoria que conseguimos fazer.",["Compare as duas gravações.","Escolha ordem das peças.","Treine entradas e finais, não outro concerto inteiro."],"Usa gravação para reconhecer progresso e melhorar um ponto."),
"5-8:48":g(["Defina a ordem de 2–3 peças.","Faça aquecimento de dois minutos.","Treine entrada, pausa entre peças e final.","Apresente sem correções do professor durante a execução."],"Hoje é dia de tocar e compartilhar, não de aprender coisa nova.",["Apresente o programa.","Diga duas conquistas específicas.","Escolha uma próxima música ou habilidade."],"Apresenta pequeno programa com continuidade e confiança.")
};