import type { ManualLessonGuide } from "@/lib/lesson-guides";
const g=(teach:string[],say:string,practice:string[],childDoes:string):ManualLessonGuide=>({teach,say,practice,childDoes});
export const guides58_13_24:Record<string,ManualLessonGuide>={
"5-8:13":g(["Mantenha um pulso lento de quatro tempos.","No mesmo pulso, fale 'ta-ka' duas vezes por batida.","Troque a fala por duas palmas iguais dentro de cada pulso.","Mostre o par de colcheias e leve-o para uma única tecla."],"O pulso continua igual; agora cabem dois sons dentro dele.",["Alterne um pulso com semínima e outro com duas colcheias.","Faça quatro padrões curtos: falar → bater → tocar.","Não permita que as colcheias façam o pulso acelerar."],"Executa pares de colcheias dentro de uma pulsação estável."),
"5-8:14":g(["Desenhe quatro caixas e conte 1–2–3–4.","Toque um som por pulso, dando ligeiro apoio ao 1.","Mostre 4/4 e explique apenas que há quatro pulsos em cada compasso.","Use semínimas, mínimas e pausas já conhecidas para preencher caixas."],"Cada compasso é uma caixa com quatro pulsos. Quando enche, começa outra.",["Monte três compassos de quatro tempos.","Conte e bata antes de tocar.","Peça que a criança confira se cada caixa tem exatamente quatro pulsos."],"Organiza figuras conhecidas dentro de 4/4 e sente o primeiro pulso."),
"5-8:15":g(["Caminhe em grupos de três: 1–2–3, 1–2–3.","Dê leve apoio ao 1 sem transformar em pancada.","Mostre 3/4 ao lado de 4/4 e compare o tamanho da caixa.","Toque três compassos com uma nota por pulso."],"Agora cada caixa termina no três. Um–dois–três, e começa de novo.",["Alterne exemplos de 3/4 e 4/4 para identificar.","Toque três compassos em 3/4.","Faça uma pequena valsa usando uma nota grave no 1 e duas leves no 2–3."],"Distingue 3/4 de 4/4 e mantém grupos de três."),
"5-8:16":g(["Separe quatro cartões: semínima, mínima, semibreve e pausa.","Monte um compasso de 4/4 e conte-o.","Troque uma figura mantendo o total correto.","Leve o ritmo montado para uma única nota e depois para a frase do repertório."],"Primeiro construímos o ritmo. Depois fazemos esse ritmo virar música.",["Monte três compassos diferentes.","Bata cada um sem piano.","Toque dois deles e identifique um padrão parecido na música do mês."],"Combina valores conhecidos e executa o compasso sem perder o pulso."),
"5-8:17":g(["Mostre a pauta sem nomes de notas.","Aponte uma sequência que sobe linha–espaço–linha e toque três teclas vizinhas subindo.","Faça o mesmo descendo.","Mostre uma nota repetida e compare o desenho com a repetição no teclado."],"A pauta é um mapa: quando o desenho sobe, o som sobe; quando desce, o som desce.",["Classifique seis desenhos como sobe, desce ou repete.","Trace com o dedo antes de tocar.","Crie um desenho simples e peça que a criança o transforme em movimento no teclado."],"Relaciona direção visual da pauta com direção no teclado."),
"5-8:18":g(["Encontre o Dó central no teclado usando as duas pretas.","Mostre onde ele fica entre as pautas da grande pauta.","Toque o Dó central e depois notas vizinhas para cima e para baixo.","Volte sempre ao Dó como ponto de partida."],"Este Dó fica no meio do nosso grande mapa. Ele vai ajudar a encontrar os vizinhos.",["Peça cinco retornos ao Dó central a partir de notas próximas.","Mostre pequenos padrões que começam no Dó.","Toque um padrão sem escrever nomes nas notas."],"Encontra Dó central no teclado e na pauta e usa-o como referência."),
"5-8:19":g(["Mostre a clave de Sol e a linha que passa pelo Sol.","Encontre esse Sol no teclado.","Mostre uma nota um passo acima e outra abaixo sem dar o nome primeiro.","Use direção e distância para encontrá-las."],"Não precisamos decorar a pauta inteira. Conhecemos o Sol e caminhamos a partir dele.",["Mostre seis notas próximas do Sol.","A criança diz primeiro a direção e só depois encontra a tecla.","Leia uma frase de quatro notas usando o Sol como âncora."],"Usa Sol como referência para ler notas próximas na clave de Sol."),
"5-8:20":g(["Mostre a clave de Fá e a linha do Fá de referência.","Encontre esse Fá na região da mão esquerda.","Mostre notas vizinhas acima e abaixo.","Compare a posição com o Dó central já conhecido."],"A clave de Fá é o mapa da região onde a mão esquerda vai trabalhar mais.",["Mostre seis notas próximas do Fá.","Leia três pequenos padrões antes de tocar.","Faça a criança localizar Fá novamente sem ajuda."],"Usa Fá como referência inicial na clave de Fá."),
"5-8:21":g(["Desenhe três padrões: nota repetida, passo e salto.","Peça que a criança descreva o formato antes de dizer qualquer nota.","Toque os três e compare também pelo ouvido.","Mostre o mesmo princípio numa frase real da partitura."],"Antes de perguntar 'qual nota?', pergunta: repetiu, andou ou saltou?",["Classifique oito pequenos padrões.","Toque quatro deles a partir de uma nota conhecida.","Encontre um passo e um salto no repertório do mês."],"Reconhece repetição, passos e saltos antes de nomear cada nota."),
"5-8:22":g(["Mostre uma frase de quatro a seis notas.","Encontre somente a primeira nota usando Dó, Sol ou Fá de referência.","Leia o desenho inteiro com o dedo: repete, sobe, desce, salta.","Só então toque a frase."],"Primeiro lê o caminho inteiro. Só depois colocamos as mãos no piano.",["Faça quatro frases curtas seguindo sempre olhar → referência → padrão → tocar.","Não permita escrever letras sobre as notas.","Repita apenas a frase em que a leitura quebrou."],"Lê uma frase curta por referência e padrão sem escrever nomes na pauta."),
"5-8:23":g(["Mostre clave de Sol em cima e clave de Fá em baixo.","Marque o Dó central entre as duas.","Aponte notas e pergunte primeiro qual mão/região pertence.","Alterne uma nota da direita e uma da esquerda."],"Não são dois mapas separados. É um piano inteiro desenhado em duas pautas.",["Faça oito apontamentos rápidos: clave, região e tecla.","Leia dois compassos alternando as mãos.","Termine voltando ao Dó central como referência comum."],"Relaciona as duas claves e alterna referências sem se perder."),
"5-8:24":g(["Abra a partitura simples da música do mês.","Antes de tocar, identifique compasso, primeira nota e padrões repetidos.","Leia a primeira frase com o dedo e depois toque.","Faça o mesmo com a segunda e una as duas."],"A partitura não serve para dizer cada resposta; ela mostra o caminho da música que já estamos aprendendo.",["Leia duas frases separadas.","Junte-as sem parar a cada erro.","Faça uma execução contínua da versão aprendida no mês."],"Usa a partitura como guia para tocar a versão mensal com continuidade.")
};