import type { ManualLessonGuide } from "@/lib/lesson-guides";
const g=(teach:string[],say:string,practice:string[],childDoes:string):ManualLessonGuide=>({teach,say,practice,childDoes});
const phases=[
["Mapa do teclado","Use grupos de 2 e 3 pretas como referências; localize Dó e Fá em várias regiões; relacione grave, médio e agudo.","O teclado repete padrões. Oriente-se por eles em vez de decorar 88 teclas."],
["Dedos e liberdade","Numere 1–5 nas duas mãos; pouse a mão naturalmente; toque cinco notas vizinhas sem elevar ombro ou endurecer punho.","Técnica começa por movimento livre, não por força."],
["Pulso e duração","Marque pulsação; pratique semínima, mínima e semibreve numa tecla; depois aplique numa frase.","Controle primeiro quando o som começa e quanto dura."],
["Pentacorde direito","Use Dó–Sol na direita; pratique subida, descida, repetição e uma frase curta.","Cinco notas já permitem fazer música."],
["Pentacorde esquerdo","Use posição confortável na esquerda; toque padrões e uma resposta musical.","A esquerda não copia a direita: trabalha com conforto e função."],
["Duas mãos","Alterne frases MD/ME e depois sustente uma base na esquerda sob uma frase direita.","Coordenação cresce por tarefas pequenas e claras."],
["Repertório mensal","Ouça a música inteira; defina versão adequada; trabalhe dois trechos e toque continuamente.","Repertório é música, não exercício disfarçado."],
["Pauta como mapa","Leia direção, repetição, passo e salto antes de nomear notas.","A pauta mostra relações e movimento."],
["Clave de Sol","Use Sol e Dó central como referências; leia vizinhos e pequenos padrões.","Leia a partir de referências, não de mnemónicas."],
["Clave de Fá","Use Fá e Dó central; leia vizinhos com a mão esquerda.","A lógica da leitura continua a mesma; muda a referência."],
["Grande pauta","Una as duas claves em torno do Dó central; alterne pequenas entradas das mãos.","É um único piano desenhado em duas pautas."],
["Leitura por padrões","Encontre primeira nota; leia contorno e intervalos; só depois toque.","Reconhecer relações reduz a tradução nota por nota."],
["Pausas e 4/4","Mantenha pulso durante silêncio; organize valores em quatro tempos.","Pausa ocupa tempo; não interrompe a música."],
["Colcheias e 3/4","Divida pulso em dois; compare grupos de três e quatro; aplique ao piano.","Subdivisão e compasso são coisas diferentes."],
["Leitura completa","Analise compasso, referências e padrões; leia peça curta sem escrever nomes.","Primeiro continuidade; depois refinamento."],
["Legato","Transfira peso entre dedos e aplique numa frase.","Legato é continuidade sem pressão."],
["Staccato","Use movimento curto e elástico; compare com legato.","Curto não significa forte."],
["Mãos juntas","Junte unidades pequenas em andamento lento e confortável.","Reduza informação antes de aumentar repetição."],
["Melodia e base","Sustente notas longas na esquerda sob melodia direita.","A esquerda cria chão para a melodia."],
["Escala de Dó","Isole passagem do polegar; toque uma oitava lentamente por mão.","A passagem continua a linha sem torcer a mão."],
["Intervalos","Compare 2ª–5ª no teclado, pauta e ouvido; encontre-os na peça.","Intervalos são distâncias reconhecíveis."],
["Dinâmica e frase","Escolha ponto de chegada; aplique p, f e crescendo sem alterar pulso.","Expressão faz parte da frase desde o início."],
["Peça a duas mãos","Mapeie dois pontos difíceis; resolva e faça execução completa.","Integre leitura, coordenação e expressão."],
["Tríades","Construa 1–3–5; toque C, F e G em bloco e quebrados.","Acorde funciona como uma unidade harmónica."],
["I–IV–V","Toque C–F–G–C e ouça tensão e repouso.","Ouça a função antes de decorar o número."],
["Inversões","Mantenha notas comuns e reduza deslocamentos entre acordes.","Inversão muda posição, não identidade."],
["Melodia e acordes","Marque trocas; pratique camadas separadas e junte por compasso.","A harmonia apoia a melodia."],
["Acompanhamento","Transforme acordes num padrão simples e estável de esquerda.","Padrão previsível libera atenção para a música."],
["Cifras","Leia C, F, G e Am; construa e aplique numa progressão.","Cifra indica harmonia; a textura é escolha."],
["Acompanhar canção","Marque trocas numa canção conhecida; toque blocos e depois padrão.","Simplifique a mão antes de sacrificar o pulso."],
["Continuidade","Execute a canção inteira; corrija só o ponto que quebra o fluxo; execute novamente.","Continuidade vem antes de polimento microscópico."],
["Pedal","Ataque, pedal depois; troque com a harmonia; compare limpo e borrado.","O pé segue o ouvido."],
["Fraseado","Cante, encontre chegada e respiração; combine dinâmica e pedal.","Fraseado organiza direção e respiração."],
["Ouvido","Reconheça sobe/desce/repete; reproduza padrões de 2–3 notas.","Ouça relações, não adivinhe notas isoladas."],
["Tirar de ouvido","Cante frase familiar; encontre primeira nota e prossiga por relações.","Cante, preveja e confirme."],
["Improvisação","Limite notas e pulsos; repita e transforme um motivo.","Improvisar é escolher dentro de limites."],
["Transposição","Mova padrão mantendo intervalos; compare pelo ouvido.","Mude o ponto de partida, preserve relações."],
["Prática inteligente","Diagnostique nota, ritmo, dedo, coordenação ou som; isole e reintegre.","Nomeie o problema antes de repetir."],
["Interpretação","Grave a peça; escolha dinâmica, fraseado e pedal; compare nova execução.","Interpretação é um conjunto de escolhas coerentes."],
["Repertório final","Escolha 2–3 peças realistas e diferentes; defina prioridades.","Programa bom mostra música preparada, não dificuldade máxima."],
["Trechos difíceis","Classifique falhas e escolha estratégia específica para duas delas.","Problema específico recebe solução específica."],
["Mãos separadas","Use estudo separado apenas onde resolve coordenação; junte logo em unidade pequena.","Mãos separadas são ferramenta, não ritual."],
["Do trecho à peça","Toque compasso antes/depois; expanda para frase e seção.","Correção só vale quando funciona no contexto."],
["Memória segura","Mapeie forma, harmonia e pontos de partida; simule recuperação.","Memória usa vários caminhos."],
["Gravar e avaliar","Grave sem parar; escolha dois critérios; trabalhe e grave de novo.","Transforme observação em ação concreta."],
["Ensaio geral","Execute programa completo sem interrupção; corrija depois apenas o essencial.","Ensaio testa a experiência inteira."],
["Recital","Aqueça brevemente; apresente 2–3 peças; registre conquistas e próximo objetivo.","Feche o ciclo tocando e definindo o próximo passo."]
] as const;
export const guidesAdult:Record<string,ManualLessonGuide>={};
for(let i=0;i<phases.length;i++){const [title,teach,say]=phases[i];const n=i+2;guidesAdult[`adult:${n}`]=g([teach,`Demonstre ${title} com um exemplo musical curto.`,"Faça o aluno repetir uma vez e ajuste apenas o que compromete o objetivo."],say,[`Pratique ${title} em duas situações curtas.`,"Aplique imediatamente no repertório ou numa frase musical.","Termine com uma tentativa contínua, sem parar a cada pequeno erro."],`Executa ${title} e consegue aplicá-lo musicalmente com menos ajuda.`);}
