export type MusicRights = "original" | "public-domain" | "license-required";

export type KidsSong = {
  id: string;
  title: string;
  subtitle: string;
  age: "2-4" | "5-8" | "both";
  difficulty: "Muito fácil" | "Fácil" | "Intermédio";
  theme: string;
  emoji: string;
  rights: MusicRights;
  playable: boolean;
  story: string;
  rightsSource?: string;
  colors?: { note: string; color: string }[];
  sequence?: string[];
};

const rainbowNotes = [
  { note: "Dó", color: "#ff5f86" },
  { note: "Ré", color: "#ffbf3f" },
  { note: "Mi", color: "#64c96b" },
  { note: "Fá", color: "#4fc8c1" },
  { note: "Sol", color: "#4b9df8" },
  { note: "Lá", color: "#8f74eb" },
  { note: "Si", color: "#d264d7" },
];

export const kidsSongs: KidsSong[] = [
  {
    id: "passeio-das-cores",
    title: "O Passeio das Cores",
    subtitle: "Uma mini música original Luwipi",
    age: "2-4",
    difficulty: "Muito fácil",
    theme: "cores e movimento",
    emoji: "🌈",
    rights: "original",
    playable: true,
    story: "Quatro cores querem atravessar o jardim musical. Cada tecla ajuda uma cor a dar um passo. Vamos levar todas até a festa?",
    colors: rainbowNotes,
    sequence: ["Dó", "Ré", "Mi", "Ré", "Dó", "Mi", "Sol", "Mi"],
  },
  {
    id: "estrelinha",
    title: "Brilha, Brilha, Estrelinha",
    subtitle: "Melodia tradicional para primeiros passos",
    age: "both",
    difficulty: "Fácil",
    theme: "céu e estrelas",
    emoji: "⭐",
    rights: "public-domain",
    playable: true,
    rightsSource: "Melodia tradicional Ah! vous dirai-je, maman / fonte histórica em domínio público.",
    story: "Uma estrelinha perdeu o caminho de volta para o céu. Cada frase musical acende uma nova estrela até o céu ficar completo.",
    colors: rainbowNotes,
    sequence: ["Dó", "Dó", "Sol", "Sol", "Lá", "Lá", "Sol", "Fá", "Fá", "Mi", "Mi", "Ré", "Ré", "Dó"],
  },
  {
    id: "maria-cordeirinho",
    title: "Maria Tinha um Cordeirinho",
    subtitle: "História musical com o Nino",
    age: "both",
    difficulty: "Fácil",
    theme: "história e imitação",
    emoji: "🐑",
    rights: "public-domain",
    playable: true,
    rightsSource: "Canção de 1830; fontes históricas em domínio público.",
    story: "Nino quer encontrar Maria. Cada sequência correta faz o cordeirinho avançar pela estrada até chegar à escola.",
    colors: rainbowNotes,
    sequence: ["Mi", "Ré", "Dó", "Ré", "Mi", "Mi", "Mi", "Ré", "Ré", "Ré", "Mi", "Sol", "Sol"],
  },
  {
    id: "frere-jacques",
    title: "Frère Jacques",
    subtitle: "O sino que acorda a vila",
    age: "both",
    difficulty: "Fácil",
    theme: "sinos e repetição",
    emoji: "🔔",
    rights: "public-domain",
    playable: true,
    rightsSource: "Canção tradicional francesa documentada no século XVIII; partitura histórica em domínio público.",
    story: "A vila ainda está dormindo. A criança toca pequenas frases para acordar os sinos, as casas e finalmente o irmão Jacques.",
    colors: rainbowNotes,
    sequence: ["Dó", "Ré", "Mi", "Dó", "Dó", "Ré", "Mi", "Dó", "Mi", "Fá", "Sol", "Mi", "Fá", "Sol"],
  },
  {
    id: "row-row-row",
    title: "Row, Row, Row Your Boat",
    subtitle: "Uma viagem de barco pelo rio musical",
    age: "both",
    difficulty: "Fácil",
    theme: "água e movimento",
    emoji: "🚣",
    rights: "public-domain",
    playable: true,
    rightsSource: "Música e letra tradicionais em domínio público; fontes históricas anteriores a 1931.",
    story: "O barquinho precisa atravessar o rio. Cada nota faz o barco remar um pouco mais até chegar à margem colorida.",
    colors: rainbowNotes,
    sequence: ["Dó", "Dó", "Dó", "Ré", "Mi", "Mi", "Ré", "Mi", "Fá", "Sol"],
  },
  {
    id: "hot-cross-buns",
    title: "Hot Cross Buns",
    subtitle: "Três notas para começar a tocar de verdade",
    age: "5-8",
    difficulty: "Muito fácil",
    theme: "padrões de 3 notas",
    emoji: "🥯",
    rights: "public-domain",
    playable: true,
    rightsSource: "Cantiga infantil documentada em coletâneas do século XIX e início do século XX.",
    story: "Três pãezinhos musicais estão saindo do forno. Cada padrão correto coloca um deles na cesta da festa.",
    colors: rainbowNotes,
    sequence: ["Mi", "Ré", "Dó", "Mi", "Ré", "Dó", "Dó", "Dó", "Dó", "Dó", "Ré", "Ré", "Ré", "Ré", "Mi", "Ré", "Dó"],
  },
  {
    id: "ciranda-cirandinha",
    title: "Ciranda, Cirandinha",
    subtitle: "Cantiga de roda para transformar ritmo em movimento",
    age: "both",
    difficulty: "Fácil",
    theme: "roda e movimento",
    emoji: "🟡",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga de roda do folclore brasileiro; letra tradicional em domínio público.",
    story: "Uma roda colorida só começa a girar quando a criança encontra o pulso certo. Cada trecho acrescenta um novo amigo à ciranda.",
  },
  {
    id: "sapo-cururu",
    title: "Sapo Cururu",
    subtitle: "Uma noite musical na beira do rio",
    age: "both",
    difficulty: "Fácil",
    theme: "animais e noite",
    emoji: "🐸",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga tradicional brasileira em domínio público.",
    story: "O sapinho está à beira do rio e precisa encontrar o caminho até sua casinha. Sons graves, suaves e pequenos padrões ajudam no percurso.",
  },
  {
    id: "sapo-nao-lava-pe",
    title: "O Sapo Não Lava o Pé",
    subtitle: "Ritmo, humor e repetição",
    age: "both",
    difficulty: "Fácil",
    theme: "animais e ritmo",
    emoji: "🫧",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga folclórica brasileira creditada como domínio público.",
    story: "O sapo deixou pegadas pela lagoa. A criança segue as pegadas com ritmo, cores e pequenas respostas no piano.",
  },
  {
    id: "a-canoa-virou",
    title: "A Canoa Virou",
    subtitle: "Uma aventura para remar no pulso certo",
    age: "both",
    difficulty: "Fácil",
    theme: "mar, pulso e nomes",
    emoji: "🛶",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga popular brasileira creditada como domínio público.",
    story: "A canoa virou e os amigos precisam voltar para bordo. Cada desafio musical resgata um personagem e ensina a manter o pulso.",
  },
  {
    id: "peixe-vivo",
    title: "Peixe Vivo",
    subtitle: "Melodia brasileira para tocar com expressão",
    age: "5-8",
    difficulty: "Intermédio",
    theme: "água e fraseado",
    emoji: "🐟",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga tradicional brasileira creditada como domínio público.",
    story: "Um peixinho atravessa águas calmas e agitadas. A criança aprende a fazer a melodia respirar, crescer e diminuir como as ondas.",
  },
  {
    id: "boi-cara-preta",
    title: "Boi da Cara Preta",
    subtitle: "Graves, passos e contrastes sonoros",
    age: "2-4",
    difficulty: "Muito fácil",
    theme: "grave e movimento",
    emoji: "🐂",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga tradicional brasileira creditada como domínio público.",
    story: "Um boi grandalhão caminha devagar pelo campo. A criança acompanha seus passos com sons graves, pausas e movimentos grandes.",
  },
  {
    id: "baby-shark",
    title: "Baby Shark",
    subtitle: "Experiência planejada para repertório popular",
    age: "both",
    difficulty: "Fácil",
    theme: "oceano e família",
    emoji: "🦈",
    rights: "license-required",
    playable: false,
    story: "A família tubarão atravessa o oceano em pequenas missões musicais, com cores, movimento e imitação.",
  },
  {
    id: "3-palavrinhas",
    title: "3 Palavrinhas",
    subtitle: "Coleção planejada de músicas infantis cristãs",
    age: "both",
    difficulty: "Fácil",
    theme: "fé, histórias e valores",
    emoji: "🎈",
    rights: "license-required",
    playable: false,
    story: "As canções entram como pequenas aventuras ilustradas, sempre com participação da criança e ligação ao piano.",
  },
];

export function getSong(id: string) {
  return kidsSongs.find((song) => song.id === id);
}
