export type MusicRights = "original" | "public-domain" | "license-required";

export type KidsSong = {
  id: string;
  title: string;
  subtitle: string;
  age: "2-4" | "5-8" | "both";
  difficulty: "Muito fácil" | "Fácil" | "Intermédio";
  theme: string;
  emoji: string;
  rights: MusicRights;
  playable: boolean;
  story: string;
  rightsSource?: string;
  colors?: { note: string; color: string }[];
  sequence?: string[];
};

const rainbowNotes = [
  { note: "Dó", color: "#ff5f86" },
  { note: "Ré", color: "#ffbf3f" },
  { note: "Mi", color: "#64c96b" },
  { note: "Fá", color: "#4fc8c1" },
  { note: "Sol", color: "#4b9df8" },
  { note: "Lá", color: "#8f74eb" },
  { note: "Si", color: "#d264d7" },
];

export const kidsSongs: KidsSong[] = [
  {
    id: "passeio-das-cores",
    title: "O Passeio das Cores",
    subtitle: "Uma mini música original Luwipi",
    age: "2-4",
    difficulty: "Muito fácil",
    theme: "cores e movimento",
    emoji: "🌈",
    rights: "original",
    playable: true,
    story: "Quatro cores querem atravessar o jardim musical. Cada tecla ajuda uma cor a dar um passo. Vamos levar todas até a festa?",
    colors: rainbowNotes,
    sequence: ["Dó", "Ré", "Mi", "Ré", "Dó", "Mi", "Sol", "Mi"],
  },
  {
    id: "estrelinha",
    title: "Brilha, Brilha, Estrelinha",
    subtitle: "Melodia tradicional para primeiros passos",
    age: "both",
    difficulty: "Fácil",
    theme: "céu e estrelas",
    emoji: "⭐",
    rights: "public-domain",
    playable: true,
    rightsSource: "Melodia tradicional do século XVIII em domínio público; experiência em português criada pelo Luwipi.",
    story: "Uma estrelinha perdeu o caminho de volta para o céu. Cada frase musical acende uma nova estrela até o céu ficar completo.",
    colors: rainbowNotes,
    sequence: ["Dó", "Dó", "Sol", "Sol", "Lá", "Lá", "Sol", "Fá", "Fá", "Mi", "Mi", "Ré", "Ré", "Dó"],
  },
  {
    id: "maria-cordeirinho",
    title: "Maria Tinha um Cordeirinho",
    subtitle: "História musical com o Nino",
    age: "both",
    difficulty: "Fácil",
    theme: "história e imitação",
    emoji: "🐑",
    rights: "public-domain",
    playable: true,
    rightsSource: "Melodia histórica do século XIX em domínio público; narrativa em português criada pelo Luwipi.",
    story: "Nino quer encontrar Maria. Cada sequência correta faz o cordeirinho avançar pela estrada até chegar à escola.",
    colors: rainbowNotes,
    sequence: ["Mi", "Ré", "Dó", "Ré", "Mi", "Mi", "Mi", "Ré", "Ré", "Ré", "Mi", "Sol", "Sol"],
  },
  {
    id: "irmao-joao",
    title: "Irmão João",
    subtitle: "O sino que acorda a vila",
    age: "both",
    difficulty: "Fácil",
    theme: "sinos e repetição",
    emoji: "🔔",
    rights: "public-domain",
    playable: true,
    rightsSource: "Melodia tradicional europeia em domínio público; experiência apresentada integralmente em português.",
    story: "A vila ainda está dormindo. A criança toca pequenas frases para acordar os sinos, as casas e finalmente o Irmão João.",
    colors: rainbowNotes,
    sequence: ["Dó", "Ré", "Mi", "Dó", "Dó", "Ré", "Mi", "Dó", "Mi", "Fá", "Sol", "Mi", "Fá", "Sol"],
  },
  {
    id: "rema-rema-barco",
    title: "Rema, Rema, Rema o Barco",
    subtitle: "Uma viagem de barco pelo rio musical",
    age: "both",
    difficulty: "Fácil",
    theme: "água e movimento",
    emoji: "🚣",
    rights: "public-domain",
    playable: true,
    rightsSource: "Melodia tradicional em domínio público; o Luwipi usa apenas a melodia e uma experiência própria em português.",
    story: "O barquinho precisa atravessar o rio. Cada nota faz o barco remar um pouco mais até chegar à margem colorida.",
    colors: rainbowNotes,
    sequence: ["Dó", "Dó", "Dó", "Ré", "Mi", "Mi", "Ré", "Mi", "Fá", "Sol"],
  },
  {
    id: "se-essa-rua-fosse-minha",
    title: "Se Essa Rua Fosse Minha",
    subtitle: "Uma rua que se constrói nota por nota",
    age: "both",
    difficulty: "Fácil",
    theme: "imaginação e fraseado",
    emoji: "🏘️",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga tradicional brasileira registrada em acervos de folclore.",
    story: "A rua começa vazia. Cada pequeno trecho musical acrescenta pedrinhas, árvores, luzes e personagens até formar uma rua encantada.",
  },
  {
    id: "ciranda-cirandinha",
    title: "Ciranda, Cirandinha",
    subtitle: "Cantiga de roda para transformar ritmo em movimento",
    age: "both",
    difficulty: "Fácil",
    theme: "roda e movimento",
    emoji: "🟡",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga de roda do folclore brasileiro.",
    story: "Uma roda colorida só começa a girar quando a criança encontra o pulso certo. Cada trecho acrescenta um novo amigo à ciranda.",
  },
  {
    id: "sapo-cururu",
    title: "Sapo Cururu",
    subtitle: "Uma noite musical na beira do rio",
    age: "both",
    difficulty: "Fácil",
    theme: "animais e noite",
    emoji: "🐸",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga tradicional brasileira.",
    story: "O sapinho está à beira do rio e precisa encontrar o caminho até sua casinha. Sons graves, suaves e pequenos padrões ajudam no percurso.",
  },
  {
    id: "sapo-nao-lava-pe",
    title: "O Sapo Não Lava o Pé",
    subtitle: "Ritmo, humor e repetição",
    age: "both",
    difficulty: "Fácil",
    theme: "animais e ritmo",
    emoji: "🫧",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga folclórica brasileira tradicional.",
    story: "O sapo deixou pegadas pela lagoa. A criança segue as pegadas com ritmo, cores e pequenas respostas no piano.",
  },
  {
    id: "a-canoa-virou",
    title: "A Canoa Virou",
    subtitle: "Uma aventura para remar no pulso certo",
    age: "both",
    difficulty: "Fácil",
    theme: "mar, pulso e nomes",
    emoji: "🛶",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga popular brasileira tradicional.",
    story: "A canoa virou e os amigos precisam voltar para bordo. Cada desafio musical resgata um personagem e ensina a manter o pulso.",
  },
  {
    id: "peixe-vivo",
    title: "Peixe Vivo",
    subtitle: "Melodia brasileira para tocar com expressão",
    age: "5-8",
    difficulty: "Intermédio",
    theme: "água e fraseado",
    emoji: "🐟",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga tradicional brasileira.",
    story: "Um peixinho atravessa águas calmas e agitadas. A criança aprende a fazer a melodia respirar, crescer e diminuir como as ondas.",
  },
  {
    id: "boi-cara-preta",
    title: "Boi da Cara Preta",
    subtitle: "Graves, passos e contrastes sonoros",
    age: "2-4",
    difficulty: "Muito fácil",
    theme: "grave e movimento",
    emoji: "🐂",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga tradicional brasileira.",
    story: "Um boi grandalhão caminha devagar pelo campo. A criança acompanha seus passos com sons graves, pausas e movimentos grandes.",
  },
  {
    id: "cai-cai-balao",
    title: "Cai, Cai, Balão",
    subtitle: "Uma aventura de festa e movimento",
    age: "both",
    difficulty: "Fácil",
    theme: "festa, altura e direção",
    emoji: "🎈",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga tradicional do folclore brasileiro.",
    story: "O balão sobe, desce e atravessa o céu. A criança acompanha o movimento com sons que sobem e descem no piano.",
  },
  {
    id: "o-cravo-e-a-rosa",
    title: "O Cravo e a Rosa",
    subtitle: "Uma história musical entre duas flores",
    age: "both",
    difficulty: "Fácil",
    theme: "história e diálogo musical",
    emoji: "🌹",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga de roda tradicional brasileira.",
    story: "O cravo e a rosa conversam através do piano. A criança responde por cada personagem usando pequenas frases musicais.",
  },
  {
    id: "escravos-de-jo",
    title: "Escravos de Jó",
    subtitle: "Pulso, coordenação e jogo coletivo",
    age: "5-8",
    difficulty: "Intermédio",
    theme: "ritmo e coordenação",
    emoji: "🪘",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga tradicional do folclore brasileiro.",
    story: "Objetos coloridos passam de mão em mão enquanto a música mantém todos juntos no mesmo pulso.",
  },
  {
    id: "marcha-soldado",
    title: "Marcha, Soldado",
    subtitle: "Passos firmes para sentir a pulsação",
    age: "both",
    difficulty: "Muito fácil",
    theme: "pulso e movimento",
    emoji: "🥁",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga tradicional brasileira.",
    story: "Um pequeno desfile atravessa a cidade. Cada pulso correto faz a banda avançar mais uma casa.",
  },
  {
    id: "terezinha-de-jesus",
    title: "Terezinha de Jesus",
    subtitle: "Uma cantiga de roda para ouvir e contar",
    age: "5-8",
    difficulty: "Fácil",
    theme: "melodia e memória",
    emoji: "🌼",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga tradicional brasileira registrada em acervos de folclore.",
    story: "Terezinha percorre um jardim musical. A criança memoriza pequenas frases para abrir cada novo caminho.",
  },
  {
    id: "alecim-dourado",
    title: "Alecrim Dourado",
    subtitle: "Uma pequena história no jardim",
    age: "both",
    difficulty: "Fácil",
    theme: "natureza e melodia",
    emoji: "🌿",
    rights: "public-domain",
    playable: false,
    rightsSource: "Cantiga tradicional do folclore brasileiro.",
    story: "No jardim do Luwipi, cada nota faz nascer uma nova folha de alecrim. Ao completar a frase, o jardim floresce.",
  },
  {
    id: "baby-shark",
    title: "Bebê Tubarão",
    subtitle: "Experiência planejada para repertório popular",
    age: "both",
    difficulty: "Fácil",
    theme: "oceano e família",
    emoji: "🦈",
    rights: "license-required",
    playable: false,
    story: "A família tubarão atravessa o oceano em pequenas missões musicais, com cores, movimento e imitação.",
  },
  {
    id: "3-palavrinhas",
    title: "3 Palavrinhas",
    subtitle: "Coleção planejada de músicas infantis cristãs",
    age: "both",
    difficulty: "Fácil",
    theme: "fé, histórias e valores",
    emoji: "🎈",
    rights: "license-required",
    playable: false,
    story: "As canções entram como pequenas aventuras ilustradas, sempre com participação da criança e ligação ao piano.",
  },
];

export function getSong(id: string) {
  return kidsSongs.find((song) => song.id === id);
}
