function json(body,status=200){return Response.json(body,{status,headers:{"cache-control":"no-store"}})}
function bytesToHex(bytes){return Array.from(new Uint8Array(bytes)).map(byte=>byte.toString(16).padStart(2,"0")).join("")}
async function hmacHex(secret,value){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return bytesToHex(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value)))}
function secureEqual(a,b){if(!a||!b||a.length!==b.length)return false;let mismatch=0;for(let i=0;i<a.length;i++)mismatch|=a.charCodeAt(i)^b.charCodeAt(i);return mismatch===0}
async function validSignature(raw,header,secret){let ts="";const hashes=[];for(const part of header.split(";")){const bits=part.split("=");if(bits[0]==="ts")ts=bits[1]||"";if(bits[0]==="h1"&&bits[1])hashes.push(bits[1])}if(!ts||!hashes.length)return false;const seconds=Number(ts);if(!Number.isFinite(seconds)||Math.abs(Date.now()/1000-seconds)>30)return false;const expected=await hmacHex(secret,ts+":"+raw);return hashes.some(hash=>secureEqual(expected,hash))}
function cfg(){return{url:process.env.SUPABASE_URL||"",secret:process.env.SUPABASE_SECRET_KEY||""}}
async function adminFetch(path,init={}){const c=cfg();if(!c.url||!c.secret)throw new Error("supabase_not_configured");const headers=new Headers(init.headers||{});headers.set("apikey",c.secret);headers.set("authorization","Bearer "+c.secret);if(init.body)headers.set("content-type","application/json");return fetch(c.url+"/rest/v1/"+path,{...init,headers})}
async function alreadyProcessed(eventId){const r=await adminFetch("billing_webhook_events?event_id=eq."+encodeURIComponent(eventId)+"&select=event_id&limit=1");if(!r.ok)throw new Error("event_lookup_failed");return(await r.json()).length>0}
async function rememberEvent(eventId,eventType){const r=await adminFetch("billing_webhook_events",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({event_id:eventId,event_type:eventType})});if(!r.ok&&r.status!==409)throw new Error("event_insert_failed")}
async function entitlement(userId,product){const r=await adminFetch("product_entitlements?user_id=eq."+encodeURIComponent(userId)+"&product=eq."+encodeURIComponent(product)+"&select=user_id,product,paddle_event_at,access_until&limit=1");if(!r.ok)throw new Error("entitlement_lookup_failed");return(await r.json())[0]||null}
async function targetBySubscription(subscriptionId){if(!subscriptionId)return null;const r=await adminFetch("product_entitlements?paddle_subscription_id=eq."+encodeURIComponent(subscriptionId)+"&select=user_id,product&limit=1");if(!r.ok)throw new Error("subscription_lookup_failed");return(await r.json())[0]||null}
async function resolveTarget(data,subId){const userId=data.custom_data&&data.custom_data.user_id,product=data.custom_data&&data.custom_data.product;if(userId&&["ensine","aprenda"].includes(product))return{user_id:String(userId),product};return targetBySubscription(subId)}
function eventTime(event){const value=String(event.occurred_at||""),ms=new Date(value).getTime();return Number.isFinite(ms)?new Date(ms).toISOString():new Date().toISOString()}
async function patchEntitlement(userId,product,patch,occurredAt){if(!["ensine","aprenda"].includes(product))throw new Error("invalid_product");const current=await entitlement(userId,product);if(current&&current.paddle_event_at&&new Date(current.paddle_event_at).getTime()>new Date(occurredAt).getTime())return false;const row={user_id:userId,product,...patch,paddle_event_at:occurredAt,updated_at:new Date().toISOString()},r=await adminFetch("product_entitlements",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(row)});if(!r.ok)throw new Error("entitlement_update_failed");return true}
function subscriptionId(data){return(typeof data.id==="string"&&data.id.startsWith("sub_")?data.id:null)||data.subscription_id||null}
function firstPriceId(data){const item=data.items&&data.items[0];return(item&&item.price&&item.price.id)||(item&&item.price_id)||null}
function periodEnd(data){return(data.current_billing_period&&data.current_billing_period.ends_at)||(data.billing_period&&data.billing_period.ends_at)||null}
function basePatch(data,subId){const patch={billing_provider:"paddle",paddle_customer_id:data.customer_id||null,paddle_subscription_id:subId,paddle_price_id:firstPriceId(data)};if(data.custom_data&&data.custom_data.plan)patch.subscription_period=data.custom_data.plan;if(data.status)patch.subscription_status=data.status;return patch}
export async function POST(request){const secret=process.env.PADDLE_WEBHOOK_SECRET;if(!secret)return json({error:"not_configured"},503);const raw=await request.text(),signature=request.headers.get("paddle-signature")||"";if(!(await validSignature(raw,signature,secret)))return json({error:"invalid_signature"},401);let event;try{event=JSON.parse(raw)}catch{return json({error:"invalid_event"},400)}const eventId=String(event.event_id||""),eventType=String(event.event_type||"unknown");if(!eventId)return json({error:"invalid_event"},400);try{if(await alreadyProcessed(eventId))return json({ok:true,duplicate:true});const data=event.data||{},subId=subscriptionId(data),occurredAt=eventTime(event),target=await resolveTarget(data,subId);if(target){const patch=basePatch(data,subId);if(eventType==="transaction.completed"){delete patch.subscription_status;if(subId){patch.status="active";patch.subscription_status="active";patch.activated_at=occurredAt;const end=periodEnd(data);if(end)patch.access_until=end}await patchEntitlement(target.user_id,target.product,patch,occurredAt)}else if(eventType.startsWith("subscription.")){const status=String(data.status||"").toLowerCase(),end=periodEnd(data);if(["canceled","paused"].includes(status)||["subscription.canceled","subscription.paused"].includes(eventType)){patch.status="expired";patch.subscription_status=status||eventType.split(".").pop();patch.access_until=data.canceled_at||data.paused_at||occurredAt}else if(["active","trialing","past_due"].includes(status)||["subscription.created","subscription.activated","subscription.resumed"].includes(eventType)){patch.status="active";patch.activated_at=occurredAt;if(end)patch.access_until=end}await patchEntitlement(target.user_id,target.product,patch,occurredAt)}}await rememberEvent(eventId,eventType);return json({ok:true})}catch(error){console.error("Paddle webhook processing failed",error);return json({error:"webhook_processing_failed"},500)}}
