function json(body,status=200){return Response.json(body,{status,headers:{"cache-control":"private, no-store"}})}
function cfg(){return{url:process.env.SUPABASE_URL||"",pub:process.env.SUPABASE_PUBLISHABLE_KEY||"",secret:process.env.SUPABASE_SECRET_KEY||""}}
async function userFromRequest(request){const c=cfg(),auth=request.headers.get("authorization")||"",token=auth.startsWith("Bearer ")?auth.slice(7):"";if(!token||!c.url||!c.pub)return null;const r=await fetch(c.url+"/auth/v1/user",{headers:{apikey:c.pub,authorization:"Bearer "+token}});if(!r.ok)return null;return{token,user:await r.json()}}
async function ownRole(id,token){const c=cfg(),r=await fetch(c.url+"/rest/v1/profiles?id=eq."+encodeURIComponent(id)+"&select=role&limit=1",{headers:{apikey:c.pub,authorization:"Bearer "+token}});if(!r.ok)return null;const rows=await r.json();return rows&&rows[0]&&rows[0].role}
function adminHeaders(){const c=cfg();if(!c.secret)throw new Error("server_not_configured");return{apikey:c.secret,authorization:"Bearer "+c.secret,"content-type":"application/json"}}
async function requireAdmin(request){const auth=await userFromRequest(request);if(!auth)return null;return(await ownRole(auth.user.id,auth.token))==="admin"?auth:null}
async function listProfiles(){const c=cfg(),r=await fetch(c.url+"/rest/v1/profiles?select=id,full_name,role,access_status,trial_started_at,trial_ends_at,access_until,subscription_status,created_at&order=created_at.desc&limit=200",{headers:adminHeaders()});if(!r.ok)throw new Error("profiles");return r.json()}
async function listAuthUsers(){const c=cfg(),r=await fetch(c.url+"/auth/v1/admin/users?page=1&per_page=200",{headers:adminHeaders()});if(!r.ok)return[];const body=await r.json();return body.users||[]}
export async function GET(request){if(!(await requireAdmin(request)))return json({error:"not_found"},404);try{const [profiles,users]=await Promise.all([listProfiles(),listAuthUsers()]),emails=new Map(users.map(u=>[u.id,u.email||""]));return json({users:profiles.map(p=>({...p,email:emails.get(p.id)||""}))})}catch(e){console.error(e);return json({error:"admin_unavailable"},503)}}
export async function PATCH(request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)return json({error:"not_found"},404);if(!(await requireAdmin(request)))return json({error:"not_found"},404);let body;try{body=await request.json()}catch{return json({error:"invalid"},400)}const id=String(body.id||""),action=String(body.action||"");if(!id||!["grant30","grant90","grant180","trial24","block"].includes(action))return json({error:"invalid"},400);const c=cfg(),check=await fetch(c.url+"/rest/v1/profiles?id=eq."+encodeURIComponent(id)+"&select=role&limit=1",{headers:adminHeaders()}),current=(await check.json())[0];if(!current)return json({error:"not_found"},404);if(current.role==="admin")return json({error:"protected_admin"},403);const now=new Date();let patch;if(action==="block")patch={access_status:"blocked",access_until:now.toISOString(),subscription_status:"blocked"};else if(action==="trial24")patch={access_status:"trial",trial_started_at:now.toISOString(),trial_ends_at:new Date(now.getTime()+86400000).toISOString(),access_until:null};else{const days=action==="grant30"?30:action==="grant90"?90:180;patch={access_status:"active",activated_at:now.toISOString(),access_until:new Date(now.getTime()+days*86400000).toISOString(),subscription_status:"manual_active"}}const r=await fetch(c.url+"/rest/v1/profiles?id=eq."+encodeURIComponent(id),{method:"PATCH",headers:{...adminHeaders(),Prefer:"return=minimal"},body:JSON.stringify(patch)});return r.ok?json({ok:true}):json({error:"update_failed"},502)}